//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skanetrafiken.Crm.OCTest.Kassagirot {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/")]
    public partial class NoUniqueCodeCreated : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> errorCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(singleResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(batchResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/")]
    public abstract partial class abstractResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long eanCodeField;
        
        private System.DateTime lastRedemptionDateField;
        
        private bool lastRedemptionDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long eanCode {
            get {
                return this.eanCodeField;
            }
            set {
                this.eanCodeField = value;
                this.RaisePropertyChanged("eanCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime lastRedemptionDate {
            get {
                return this.lastRedemptionDateField;
            }
            set {
                this.lastRedemptionDateField = value;
                this.RaisePropertyChanged("lastRedemptionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastRedemptionDateSpecified {
            get {
                return this.lastRedemptionDateFieldSpecified;
            }
            set {
                this.lastRedemptionDateFieldSpecified = value;
                this.RaisePropertyChanged("lastRedemptionDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/")]
    public partial class singleResponse : abstractResponse {
        
        private string uniqueCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string uniqueCode {
            get {
                return this.uniqueCodeField;
            }
            set {
                this.uniqueCodeField = value;
                this.RaisePropertyChanged("uniqueCode");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/")]
    public partial class batchResponse : abstractResponse {
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(eanCodeRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(campaignNumberRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(campaignNumberRequestWithAddress))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(campaignNumberBatchRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/")]
    public abstract partial class abstractRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int validityInDaysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int validityInDays {
            get {
                return this.validityInDaysField;
            }
            set {
                this.validityInDaysField = value;
                this.RaisePropertyChanged("validityInDays");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/")]
    public partial class eanCodeRequest : abstractRequest {
        
        private long eanCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long eanCode {
            get {
                return this.eanCodeField;
            }
            set {
                this.eanCodeField = value;
                this.RaisePropertyChanged("eanCode");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(campaignNumberRequestWithAddress))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(campaignNumberBatchRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/")]
    public partial class campaignNumberRequest : abstractRequest {
        
        private int campaignNumberField;
        
        private decimal amountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int campaignNumber {
            get {
                return this.campaignNumberField;
            }
            set {
                this.campaignNumberField = value;
                this.RaisePropertyChanged("campaignNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/")]
    public partial class campaignNumberRequestWithAddress : campaignNumberRequest {
        
        private string firstNameField;
        
        private string familyNameField;
        
        private string socialSecurityNumberField;
        
        private string streetField;
        
        private int streetNumberField;
        
        private string coAddressField;
        
        private int zipCodeField;
        
        private string cityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string familyName {
            get {
                return this.familyNameField;
            }
            set {
                this.familyNameField = value;
                this.RaisePropertyChanged("familyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string socialSecurityNumber {
            get {
                return this.socialSecurityNumberField;
            }
            set {
                this.socialSecurityNumberField = value;
                this.RaisePropertyChanged("socialSecurityNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int streetNumber {
            get {
                return this.streetNumberField;
            }
            set {
                this.streetNumberField = value;
                this.RaisePropertyChanged("streetNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string coAddress {
            get {
                return this.coAddressField;
            }
            set {
                this.coAddressField = value;
                this.RaisePropertyChanged("coAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int zipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("zipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/")]
    public partial class campaignNumberBatchRequest : campaignNumberRequest {
        
        private int quantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("quantity");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/")]
    public partial class InvalidCampaign : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> errorCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/")]
    public partial class InvalidAmount : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> errorCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/")]
    public partial class InvalidConfiguration : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> errorCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/")]
    public partial class InternalError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> errorCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/")]
    public partial class InvalidField : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> errorCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/")]
    public partial class InvalidEanCode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> errorCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/", ConfigurationName="OCTest.Kassagirot.CouponCreatorService")]
    public interface CouponCreatorService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Skanetrafiken.Crm.OCTest.Kassagirot.NoUniqueCodeCreated), Action="", Name="NoUniqueCodeCreated")]
        [System.ServiceModel.FaultContractAttribute(typeof(Skanetrafiken.Crm.OCTest.Kassagirot.InvalidCampaign), Action="", Name="InvalidCampaign")]
        [System.ServiceModel.FaultContractAttribute(typeof(Skanetrafiken.Crm.OCTest.Kassagirot.InvalidAmount), Action="", Name="InvalidAmount")]
        [System.ServiceModel.FaultContractAttribute(typeof(Skanetrafiken.Crm.OCTest.Kassagirot.InvalidConfiguration), Action="", Name="InvalidConfiguration")]
        [System.ServiceModel.FaultContractAttribute(typeof(Skanetrafiken.Crm.OCTest.Kassagirot.InternalError), Action="", Name="InternalError")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractRequest))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponBatchResponse createUniqueCouponBatch(Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponBatch request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponBatchResponse> createUniqueCouponBatchAsync(Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponBatch request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Skanetrafiken.Crm.OCTest.Kassagirot.NoUniqueCodeCreated), Action="", Name="NoUniqueCodeCreated")]
        [System.ServiceModel.FaultContractAttribute(typeof(Skanetrafiken.Crm.OCTest.Kassagirot.InvalidCampaign), Action="", Name="InvalidCampaign")]
        [System.ServiceModel.FaultContractAttribute(typeof(Skanetrafiken.Crm.OCTest.Kassagirot.InvalidAmount), Action="", Name="InvalidAmount")]
        [System.ServiceModel.FaultContractAttribute(typeof(Skanetrafiken.Crm.OCTest.Kassagirot.InvalidConfiguration), Action="", Name="InvalidConfiguration")]
        [System.ServiceModel.FaultContractAttribute(typeof(Skanetrafiken.Crm.OCTest.Kassagirot.InternalError), Action="", Name="InternalError")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractRequest))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponResponse createUniqueCoupon(Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCoupon request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponResponse> createUniqueCouponAsync(Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCoupon request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Skanetrafiken.Crm.OCTest.Kassagirot.NoUniqueCodeCreated), Action="", Name="NoUniqueCodeCreated")]
        [System.ServiceModel.FaultContractAttribute(typeof(Skanetrafiken.Crm.OCTest.Kassagirot.InvalidCampaign), Action="", Name="InvalidCampaign")]
        [System.ServiceModel.FaultContractAttribute(typeof(Skanetrafiken.Crm.OCTest.Kassagirot.InvalidAmount), Action="", Name="InvalidAmount")]
        [System.ServiceModel.FaultContractAttribute(typeof(Skanetrafiken.Crm.OCTest.Kassagirot.InvalidConfiguration), Action="", Name="InvalidConfiguration")]
        [System.ServiceModel.FaultContractAttribute(typeof(Skanetrafiken.Crm.OCTest.Kassagirot.InternalError), Action="", Name="InternalError")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractRequest))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Skanetrafiken.Crm.OCTest.Kassagirot.createMobileCouponResponse createMobileCoupon(Skanetrafiken.Crm.OCTest.Kassagirot.createMobileCoupon request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Skanetrafiken.Crm.OCTest.Kassagirot.createMobileCouponResponse> createMobileCouponAsync(Skanetrafiken.Crm.OCTest.Kassagirot.createMobileCoupon request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Skanetrafiken.Crm.OCTest.Kassagirot.InvalidField), Action="", Name="InvalidField")]
        [System.ServiceModel.FaultContractAttribute(typeof(Skanetrafiken.Crm.OCTest.Kassagirot.InvalidCampaign), Action="", Name="InvalidCampaign")]
        [System.ServiceModel.FaultContractAttribute(typeof(Skanetrafiken.Crm.OCTest.Kassagirot.InvalidAmount), Action="", Name="InvalidAmount")]
        [System.ServiceModel.FaultContractAttribute(typeof(Skanetrafiken.Crm.OCTest.Kassagirot.InvalidConfiguration), Action="", Name="InvalidConfiguration")]
        [System.ServiceModel.FaultContractAttribute(typeof(Skanetrafiken.Crm.OCTest.Kassagirot.InternalError), Action="", Name="InternalError")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractRequest))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Skanetrafiken.Crm.OCTest.Kassagirot.createCouponForPrintingResponse createCouponForPrinting(Skanetrafiken.Crm.OCTest.Kassagirot.createCouponForPrinting request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Skanetrafiken.Crm.OCTest.Kassagirot.createCouponForPrintingResponse> createCouponForPrintingAsync(Skanetrafiken.Crm.OCTest.Kassagirot.createCouponForPrinting request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractRequest))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Skanetrafiken.Crm.OCTest.Kassagirot.getHeartbeatResponse getHeartbeat(Skanetrafiken.Crm.OCTest.Kassagirot.getHeartbeat request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Skanetrafiken.Crm.OCTest.Kassagirot.getHeartbeatResponse> getHeartbeatAsync(Skanetrafiken.Crm.OCTest.Kassagirot.getHeartbeat request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Skanetrafiken.Crm.OCTest.Kassagirot.InvalidEanCode), Action="", Name="InvalidEanCode")]
        [System.ServiceModel.FaultContractAttribute(typeof(Skanetrafiken.Crm.OCTest.Kassagirot.NoUniqueCodeCreated), Action="", Name="NoUniqueCodeCreated")]
        [System.ServiceModel.FaultContractAttribute(typeof(Skanetrafiken.Crm.OCTest.Kassagirot.InvalidCampaign), Action="", Name="InvalidCampaign")]
        [System.ServiceModel.FaultContractAttribute(typeof(Skanetrafiken.Crm.OCTest.Kassagirot.InvalidAmount), Action="", Name="InvalidAmount")]
        [System.ServiceModel.FaultContractAttribute(typeof(Skanetrafiken.Crm.OCTest.Kassagirot.InvalidConfiguration), Action="", Name="InvalidConfiguration")]
        [System.ServiceModel.FaultContractAttribute(typeof(Skanetrafiken.Crm.OCTest.Kassagirot.InternalError), Action="", Name="InternalError")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractRequest))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponWithEanCodeResponse createUniqueCouponWithEanCode(Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponWithEanCode request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponWithEanCodeResponse> createUniqueCouponWithEanCodeAsync(Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponWithEanCode request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createUniqueCouponBatch", WrapperNamespace="http://service.web.couponcreator.kuponginlosen.se/", IsWrapped=true)]
    public partial class createUniqueCouponBatch {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Skanetrafiken.Crm.OCTest.Kassagirot.campaignNumberBatchRequest campaignNumberBatchRequest;
        
        public createUniqueCouponBatch() {
        }
        
        public createUniqueCouponBatch(Skanetrafiken.Crm.OCTest.Kassagirot.campaignNumberBatchRequest campaignNumberBatchRequest) {
            this.campaignNumberBatchRequest = campaignNumberBatchRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createUniqueCouponBatchResponse", WrapperNamespace="http://service.web.couponcreator.kuponginlosen.se/", IsWrapped=true)]
    public partial class createUniqueCouponBatchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Skanetrafiken.Crm.OCTest.Kassagirot.batchResponse @return;
        
        public createUniqueCouponBatchResponse() {
        }
        
        public createUniqueCouponBatchResponse(Skanetrafiken.Crm.OCTest.Kassagirot.batchResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createUniqueCoupon", WrapperNamespace="http://service.web.couponcreator.kuponginlosen.se/", IsWrapped=true)]
    public partial class createUniqueCoupon {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Skanetrafiken.Crm.OCTest.Kassagirot.campaignNumberRequest campaignNumberRequest;
        
        public createUniqueCoupon() {
        }
        
        public createUniqueCoupon(Skanetrafiken.Crm.OCTest.Kassagirot.campaignNumberRequest campaignNumberRequest) {
            this.campaignNumberRequest = campaignNumberRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createUniqueCouponResponse", WrapperNamespace="http://service.web.couponcreator.kuponginlosen.se/", IsWrapped=true)]
    public partial class createUniqueCouponResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Skanetrafiken.Crm.OCTest.Kassagirot.singleResponse @return;
        
        public createUniqueCouponResponse() {
        }
        
        public createUniqueCouponResponse(Skanetrafiken.Crm.OCTest.Kassagirot.singleResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createMobileCoupon", WrapperNamespace="http://service.web.couponcreator.kuponginlosen.se/", IsWrapped=true)]
    public partial class createMobileCoupon {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Skanetrafiken.Crm.OCTest.Kassagirot.campaignNumberRequest campaignNumberRequest;
        
        public createMobileCoupon() {
        }
        
        public createMobileCoupon(Skanetrafiken.Crm.OCTest.Kassagirot.campaignNumberRequest campaignNumberRequest) {
            this.campaignNumberRequest = campaignNumberRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createMobileCouponResponse", WrapperNamespace="http://service.web.couponcreator.kuponginlosen.se/", IsWrapped=true)]
    public partial class createMobileCouponResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Skanetrafiken.Crm.OCTest.Kassagirot.singleResponse @return;
        
        public createMobileCouponResponse() {
        }
        
        public createMobileCouponResponse(Skanetrafiken.Crm.OCTest.Kassagirot.singleResponse @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/")]
    public partial class couponForPrintingResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long referenceNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long referenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
                this.RaisePropertyChanged("referenceNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createCouponForPrinting", WrapperNamespace="http://service.web.couponcreator.kuponginlosen.se/", IsWrapped=true)]
    public partial class createCouponForPrinting {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Skanetrafiken.Crm.OCTest.Kassagirot.campaignNumberRequestWithAddress campaignNumberRequestWithAddress;
        
        public createCouponForPrinting() {
        }
        
        public createCouponForPrinting(Skanetrafiken.Crm.OCTest.Kassagirot.campaignNumberRequestWithAddress campaignNumberRequestWithAddress) {
            this.campaignNumberRequestWithAddress = campaignNumberRequestWithAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createCouponForPrintingResponse", WrapperNamespace="http://service.web.couponcreator.kuponginlosen.se/", IsWrapped=true)]
    public partial class createCouponForPrintingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Skanetrafiken.Crm.OCTest.Kassagirot.couponForPrintingResponse @return;
        
        public createCouponForPrintingResponse() {
        }
        
        public createCouponForPrintingResponse(Skanetrafiken.Crm.OCTest.Kassagirot.couponForPrintingResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHeartbeat", WrapperNamespace="http://service.web.couponcreator.kuponginlosen.se/", IsWrapped=true)]
    public partial class getHeartbeat {
        
        public getHeartbeat() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHeartbeatResponse", WrapperNamespace="http://service.web.couponcreator.kuponginlosen.se/", IsWrapped=true)]
    public partial class getHeartbeatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getHeartbeatResponse() {
        }
        
        public getHeartbeatResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createUniqueCouponWithEanCode", WrapperNamespace="http://service.web.couponcreator.kuponginlosen.se/", IsWrapped=true)]
    public partial class createUniqueCouponWithEanCode {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Skanetrafiken.Crm.OCTest.Kassagirot.eanCodeRequest eanCodeRequest;
        
        public createUniqueCouponWithEanCode() {
        }
        
        public createUniqueCouponWithEanCode(Skanetrafiken.Crm.OCTest.Kassagirot.eanCodeRequest eanCodeRequest) {
            this.eanCodeRequest = eanCodeRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createUniqueCouponWithEanCodeResponse", WrapperNamespace="http://service.web.couponcreator.kuponginlosen.se/", IsWrapped=true)]
    public partial class createUniqueCouponWithEanCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.web.couponcreator.kuponginlosen.se/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Skanetrafiken.Crm.OCTest.Kassagirot.singleResponse @return;
        
        public createUniqueCouponWithEanCodeResponse() {
        }
        
        public createUniqueCouponWithEanCodeResponse(Skanetrafiken.Crm.OCTest.Kassagirot.singleResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CouponCreatorServiceChannel : Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CouponCreatorServiceClient : System.ServiceModel.ClientBase<Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService>, Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService {
        
        public CouponCreatorServiceClient() {
        }
        
        public CouponCreatorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CouponCreatorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CouponCreatorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CouponCreatorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponBatchResponse Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService.createUniqueCouponBatch(Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponBatch request) {
            return base.Channel.createUniqueCouponBatch(request);
        }
        
        public Skanetrafiken.Crm.OCTest.Kassagirot.batchResponse createUniqueCouponBatch(Skanetrafiken.Crm.OCTest.Kassagirot.campaignNumberBatchRequest campaignNumberBatchRequest) {
            Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponBatch inValue = new Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponBatch();
            inValue.campaignNumberBatchRequest = campaignNumberBatchRequest;
            Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponBatchResponse retVal = ((Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService)(this)).createUniqueCouponBatch(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponBatchResponse> Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService.createUniqueCouponBatchAsync(Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponBatch request) {
            return base.Channel.createUniqueCouponBatchAsync(request);
        }
        
        public System.Threading.Tasks.Task<Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponBatchResponse> createUniqueCouponBatchAsync(Skanetrafiken.Crm.OCTest.Kassagirot.campaignNumberBatchRequest campaignNumberBatchRequest) {
            Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponBatch inValue = new Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponBatch();
            inValue.campaignNumberBatchRequest = campaignNumberBatchRequest;
            return ((Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService)(this)).createUniqueCouponBatchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponResponse Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService.createUniqueCoupon(Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCoupon request) {
            return base.Channel.createUniqueCoupon(request);
        }
        
        public Skanetrafiken.Crm.OCTest.Kassagirot.singleResponse createUniqueCoupon(Skanetrafiken.Crm.OCTest.Kassagirot.campaignNumberRequest campaignNumberRequest) {
            Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCoupon inValue = new Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCoupon();
            inValue.campaignNumberRequest = campaignNumberRequest;
            Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponResponse retVal = ((Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService)(this)).createUniqueCoupon(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponResponse> Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService.createUniqueCouponAsync(Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCoupon request) {
            return base.Channel.createUniqueCouponAsync(request);
        }
        
        public System.Threading.Tasks.Task<Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponResponse> createUniqueCouponAsync(Skanetrafiken.Crm.OCTest.Kassagirot.campaignNumberRequest campaignNumberRequest) {
            Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCoupon inValue = new Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCoupon();
            inValue.campaignNumberRequest = campaignNumberRequest;
            return ((Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService)(this)).createUniqueCouponAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Skanetrafiken.Crm.OCTest.Kassagirot.createMobileCouponResponse Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService.createMobileCoupon(Skanetrafiken.Crm.OCTest.Kassagirot.createMobileCoupon request) {
            return base.Channel.createMobileCoupon(request);
        }
        
        public Skanetrafiken.Crm.OCTest.Kassagirot.singleResponse createMobileCoupon(Skanetrafiken.Crm.OCTest.Kassagirot.campaignNumberRequest campaignNumberRequest) {
            Skanetrafiken.Crm.OCTest.Kassagirot.createMobileCoupon inValue = new Skanetrafiken.Crm.OCTest.Kassagirot.createMobileCoupon();
            inValue.campaignNumberRequest = campaignNumberRequest;
            Skanetrafiken.Crm.OCTest.Kassagirot.createMobileCouponResponse retVal = ((Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService)(this)).createMobileCoupon(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Skanetrafiken.Crm.OCTest.Kassagirot.createMobileCouponResponse> Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService.createMobileCouponAsync(Skanetrafiken.Crm.OCTest.Kassagirot.createMobileCoupon request) {
            return base.Channel.createMobileCouponAsync(request);
        }
        
        public System.Threading.Tasks.Task<Skanetrafiken.Crm.OCTest.Kassagirot.createMobileCouponResponse> createMobileCouponAsync(Skanetrafiken.Crm.OCTest.Kassagirot.campaignNumberRequest campaignNumberRequest) {
            Skanetrafiken.Crm.OCTest.Kassagirot.createMobileCoupon inValue = new Skanetrafiken.Crm.OCTest.Kassagirot.createMobileCoupon();
            inValue.campaignNumberRequest = campaignNumberRequest;
            return ((Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService)(this)).createMobileCouponAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Skanetrafiken.Crm.OCTest.Kassagirot.createCouponForPrintingResponse Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService.createCouponForPrinting(Skanetrafiken.Crm.OCTest.Kassagirot.createCouponForPrinting request) {
            return base.Channel.createCouponForPrinting(request);
        }
        
        public Skanetrafiken.Crm.OCTest.Kassagirot.couponForPrintingResponse createCouponForPrinting(Skanetrafiken.Crm.OCTest.Kassagirot.campaignNumberRequestWithAddress campaignNumberRequestWithAddress) {
            Skanetrafiken.Crm.OCTest.Kassagirot.createCouponForPrinting inValue = new Skanetrafiken.Crm.OCTest.Kassagirot.createCouponForPrinting();
            inValue.campaignNumberRequestWithAddress = campaignNumberRequestWithAddress;
            Skanetrafiken.Crm.OCTest.Kassagirot.createCouponForPrintingResponse retVal = ((Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService)(this)).createCouponForPrinting(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Skanetrafiken.Crm.OCTest.Kassagirot.createCouponForPrintingResponse> Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService.createCouponForPrintingAsync(Skanetrafiken.Crm.OCTest.Kassagirot.createCouponForPrinting request) {
            return base.Channel.createCouponForPrintingAsync(request);
        }
        
        public System.Threading.Tasks.Task<Skanetrafiken.Crm.OCTest.Kassagirot.createCouponForPrintingResponse> createCouponForPrintingAsync(Skanetrafiken.Crm.OCTest.Kassagirot.campaignNumberRequestWithAddress campaignNumberRequestWithAddress) {
            Skanetrafiken.Crm.OCTest.Kassagirot.createCouponForPrinting inValue = new Skanetrafiken.Crm.OCTest.Kassagirot.createCouponForPrinting();
            inValue.campaignNumberRequestWithAddress = campaignNumberRequestWithAddress;
            return ((Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService)(this)).createCouponForPrintingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Skanetrafiken.Crm.OCTest.Kassagirot.getHeartbeatResponse Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService.getHeartbeat(Skanetrafiken.Crm.OCTest.Kassagirot.getHeartbeat request) {
            return base.Channel.getHeartbeat(request);
        }
        
        public string getHeartbeat() {
            Skanetrafiken.Crm.OCTest.Kassagirot.getHeartbeat inValue = new Skanetrafiken.Crm.OCTest.Kassagirot.getHeartbeat();
            Skanetrafiken.Crm.OCTest.Kassagirot.getHeartbeatResponse retVal = ((Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService)(this)).getHeartbeat(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Skanetrafiken.Crm.OCTest.Kassagirot.getHeartbeatResponse> Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService.getHeartbeatAsync(Skanetrafiken.Crm.OCTest.Kassagirot.getHeartbeat request) {
            return base.Channel.getHeartbeatAsync(request);
        }
        
        public System.Threading.Tasks.Task<Skanetrafiken.Crm.OCTest.Kassagirot.getHeartbeatResponse> getHeartbeatAsync() {
            Skanetrafiken.Crm.OCTest.Kassagirot.getHeartbeat inValue = new Skanetrafiken.Crm.OCTest.Kassagirot.getHeartbeat();
            return ((Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService)(this)).getHeartbeatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponWithEanCodeResponse Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService.createUniqueCouponWithEanCode(Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponWithEanCode request) {
            return base.Channel.createUniqueCouponWithEanCode(request);
        }
        
        public Skanetrafiken.Crm.OCTest.Kassagirot.singleResponse createUniqueCouponWithEanCode(Skanetrafiken.Crm.OCTest.Kassagirot.eanCodeRequest eanCodeRequest) {
            Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponWithEanCode inValue = new Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponWithEanCode();
            inValue.eanCodeRequest = eanCodeRequest;
            Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponWithEanCodeResponse retVal = ((Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService)(this)).createUniqueCouponWithEanCode(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponWithEanCodeResponse> Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService.createUniqueCouponWithEanCodeAsync(Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponWithEanCode request) {
            return base.Channel.createUniqueCouponWithEanCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponWithEanCodeResponse> createUniqueCouponWithEanCodeAsync(Skanetrafiken.Crm.OCTest.Kassagirot.eanCodeRequest eanCodeRequest) {
            Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponWithEanCode inValue = new Skanetrafiken.Crm.OCTest.Kassagirot.createUniqueCouponWithEanCode();
            inValue.eanCodeRequest = eanCodeRequest;
            return ((Skanetrafiken.Crm.OCTest.Kassagirot.CouponCreatorService)(this)).createUniqueCouponWithEanCodeAsync(inValue);
        }
    }
}
