//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Skanetrafiken.Crm {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Skanetrafiken.Crm")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="Skanetrafiken.Crm", IsNullable=false)]
    public partial class ContactInfo : CustomerInfo {
        
        private bool isEmailChangeInProgressField;
        
        private bool isEmailChangeInProgressFieldSpecified;
        
        private ContactInfoSpecAddressBlock specAddressBlockField;
        
        /// <remarks/>
        public bool isEmailChangeInProgress {
            get {
                return this.isEmailChangeInProgressField;
            }
            set {
                this.isEmailChangeInProgressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isEmailChangeInProgressSpecified {
            get {
                return this.isEmailChangeInProgressFieldSpecified;
            }
            set {
                this.isEmailChangeInProgressFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ContactInfoSpecAddressBlock SpecAddressBlock {
            get {
                return this.specAddressBlockField;
            }
            set {
                this.specAddressBlockField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Skanetrafiken.Crm")]
    public partial class ContactInfoSpecAddressBlock {
        
        private string coField;
        
        private string line1Field;
        
        private string postalCodeField;
        
        private string cityField;
        
        private string countryNameField;
        
        /// <remarks/>
        public string CO {
            get {
                return this.coField;
            }
            set {
                this.coField = value;
            }
        }
        
        /// <remarks/>
        public string Line1 {
            get {
                return this.line1Field;
            }
            set {
                this.line1Field = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string CountryName {
            get {
                return this.countryNameField;
            }
            set {
                this.countryNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Skanetrafiken.Crm")]
    public partial class CustomerInfo {
        
        private int sourceField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private CustomerInfoAddressBlock addressBlockField;
        
        private CustomerInfoCompanyRole[] companyRoleField;
        
        private string telephoneField;
        
        private string mobileField;
        
        private string socialSecurityNumberField;
        
        private bool swedishSocialSecurityNumberField;
        
        private bool swedishSocialSecurityNumberFieldSpecified;
        
        private string emailField;
        
        private bool creditsafeOkField;
        
        private bool creditsafeOkFieldSpecified;
        
        private bool avlidenField;
        
        private bool avlidenFieldSpecified;
        
        private bool skyddadField;
        
        private bool skyddadFieldSpecified;
        
        private bool utvandradField;
        
        private bool utvandradFieldSpecified;
        
        private bool emailInvalidField;
        
        private bool emailInvalidFieldSpecified;
        
        private string newEmailField;
        
        private string guidField;
        
        private string mklIdField;
        
        private bool isLockedPortalField;
        
        private bool isLockedPortalFieldSpecified;
        
        private bool isAddressEnteredManuallyField;
        
        private bool isAddressEnteredManuallyFieldSpecified;
        
        private bool isAddressInformationCompleteField;
        
        private bool isAddressInformationCompleteFieldSpecified;
        
        /// <remarks/>
        public int Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public CustomerInfoAddressBlock AddressBlock {
            get {
                return this.addressBlockField;
            }
            set {
                this.addressBlockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CompanyRole")]
        public CustomerInfoCompanyRole[] CompanyRole {
            get {
                return this.companyRoleField;
            }
            set {
                this.companyRoleField = value;
            }
        }
        
        /// <remarks/>
        public string Telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
            }
        }
        
        /// <remarks/>
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        public string SocialSecurityNumber {
            get {
                return this.socialSecurityNumberField;
            }
            set {
                this.socialSecurityNumberField = value;
            }
        }
        
        /// <remarks/>
        public bool SwedishSocialSecurityNumber {
            get {
                return this.swedishSocialSecurityNumberField;
            }
            set {
                this.swedishSocialSecurityNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SwedishSocialSecurityNumberSpecified {
            get {
                return this.swedishSocialSecurityNumberFieldSpecified;
            }
            set {
                this.swedishSocialSecurityNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public bool CreditsafeOk {
            get {
                return this.creditsafeOkField;
            }
            set {
                this.creditsafeOkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreditsafeOkSpecified {
            get {
                return this.creditsafeOkFieldSpecified;
            }
            set {
                this.creditsafeOkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Avliden {
            get {
                return this.avlidenField;
            }
            set {
                this.avlidenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AvlidenSpecified {
            get {
                return this.avlidenFieldSpecified;
            }
            set {
                this.avlidenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Skyddad {
            get {
                return this.skyddadField;
            }
            set {
                this.skyddadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SkyddadSpecified {
            get {
                return this.skyddadFieldSpecified;
            }
            set {
                this.skyddadFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Utvandrad {
            get {
                return this.utvandradField;
            }
            set {
                this.utvandradField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UtvandradSpecified {
            get {
                return this.utvandradFieldSpecified;
            }
            set {
                this.utvandradFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool EmailInvalid {
            get {
                return this.emailInvalidField;
            }
            set {
                this.emailInvalidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EmailInvalidSpecified {
            get {
                return this.emailInvalidFieldSpecified;
            }
            set {
                this.emailInvalidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string NewEmail {
            get {
                return this.newEmailField;
            }
            set {
                this.newEmailField = value;
            }
        }
        
        /// <remarks/>
        public string Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
            }
        }
        
        /// <remarks/>
        public string MklId {
            get {
                return this.mklIdField;
            }
            set {
                this.mklIdField = value;
            }
        }
        
        /// <remarks/>
        public bool isLockedPortal {
            get {
                return this.isLockedPortalField;
            }
            set {
                this.isLockedPortalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isLockedPortalSpecified {
            get {
                return this.isLockedPortalFieldSpecified;
            }
            set {
                this.isLockedPortalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool isAddressEnteredManually {
            get {
                return this.isAddressEnteredManuallyField;
            }
            set {
                this.isAddressEnteredManuallyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isAddressEnteredManuallySpecified {
            get {
                return this.isAddressEnteredManuallyFieldSpecified;
            }
            set {
                this.isAddressEnteredManuallyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool isAddressInformationComplete {
            get {
                return this.isAddressInformationCompleteField;
            }
            set {
                this.isAddressInformationCompleteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isAddressInformationCompleteSpecified {
            get {
                return this.isAddressInformationCompleteFieldSpecified;
            }
            set {
                this.isAddressInformationCompleteFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Skanetrafiken.Crm")]
    public partial class CustomerInfoAddressBlock {
        
        private string coField;
        
        private string line1Field;
        
        private string postalCodeField;
        
        private string cityField;
        
        private string countryISOField;
        
        /// <remarks/>
        public string CO {
            get {
                return this.coField;
            }
            set {
                this.coField = value;
            }
        }
        
        /// <remarks/>
        public string Line1 {
            get {
                return this.line1Field;
            }
            set {
                this.line1Field = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string CountryISO {
            get {
                return this.countryISOField;
            }
            set {
                this.countryISOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Skanetrafiken.Crm")]
    public partial class CustomerInfoCompanyRole {
        
        private string portalIdField;
        
        private int companyRoleField;
        
        private bool companyRoleFieldSpecified;
        
        private string emailField;
        
        private string telephoneField;
        
        private bool deleteCompanyRoleField;
        
        private bool deleteCompanyRoleFieldSpecified;
        
        private bool isLockedPortalField;
        
        private bool isLockedPortalFieldSpecified;
        
        /// <remarks/>
        public string PortalId {
            get {
                return this.portalIdField;
            }
            set {
                this.portalIdField = value;
            }
        }
        
        /// <remarks/>
        public int CompanyRole {
            get {
                return this.companyRoleField;
            }
            set {
                this.companyRoleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CompanyRoleSpecified {
            get {
                return this.companyRoleFieldSpecified;
            }
            set {
                this.companyRoleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
            }
        }
        
        /// <remarks/>
        public bool deleteCompanyRole {
            get {
                return this.deleteCompanyRoleField;
            }
            set {
                this.deleteCompanyRoleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deleteCompanyRoleSpecified {
            get {
                return this.deleteCompanyRoleFieldSpecified;
            }
            set {
                this.deleteCompanyRoleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool isLockedPortal {
            get {
                return this.isLockedPortalField;
            }
            set {
                this.isLockedPortalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isLockedPortalSpecified {
            get {
                return this.isLockedPortalFieldSpecified;
            }
            set {
                this.isLockedPortalFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Skanetrafiken.Crm")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="Skanetrafiken.Crm", IsNullable=false)]
    public partial class LeadInfo : CustomerInfo {
        
        private string campaignCodeField;
        
        private string campaignIdField;
        
        private bool isCampaignActiveField;
        
        private bool isCampaignActiveFieldSpecified;
        
        private int campaignDiscountPercentField;
        
        private bool campaignDiscountPercentFieldSpecified;
        
        private string[] campaignProductsField;
        
        /// <remarks/>
        public string CampaignCode {
            get {
                return this.campaignCodeField;
            }
            set {
                this.campaignCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CampaignId {
            get {
                return this.campaignIdField;
            }
            set {
                this.campaignIdField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCampaignActive {
            get {
                return this.isCampaignActiveField;
            }
            set {
                this.isCampaignActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsCampaignActiveSpecified {
            get {
                return this.isCampaignActiveFieldSpecified;
            }
            set {
                this.isCampaignActiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int CampaignDiscountPercent {
            get {
                return this.campaignDiscountPercentField;
            }
            set {
                this.campaignDiscountPercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CampaignDiscountPercentSpecified {
            get {
                return this.campaignDiscountPercentFieldSpecified;
            }
            set {
                this.campaignDiscountPercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CampaignProducts")]
        public string[] CampaignProducts {
            get {
                return this.campaignProductsField;
            }
            set {
                this.campaignProductsField = value;
            }
        }
    }
}
