//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SR.Generated
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum abssr_PermitType1
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Färdtjänst", 0, "#0000ff")]
		Frdtjnst = 700000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Riksfärdtjänst", 1, "#0000ff")]
		Riksfrdtjnst = 700000001,
	}
}