//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SR.Generated
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum abssr_transportservice_abssr_traveltypes
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Buss eller tåg", 0, "#0000ff")]
		Bussellertg = 700000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Personbil", 1, "#0000ff")]
		Personbil = 700000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Flyg", 2, "#0000ff")]
		Flyg = 700000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Specialfordon", 3, "#0000ff")]
		Specialfordon = 700000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Båt", 4, "#0000ff")]
		Bt = 700000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Annat", 5, "#0000ff")]
		Annat = 700000005,
	}
}