

--
-- report view for plugintypestatistic
--
create view dbo.[FilteredPluginTypeStatistic] (
    [averageexecutetimeinmilliseconds],
    [crashcontributionpercent],
    [crashcount],
    [crashpercent],
    [createdby],
    [createdbyname],
    [createdon],
    [createdonutc],
    [createdonbehalfby],
    [createdonbehalfbydsc],
    [createdonbehalfbyname],
    [createdonbehalfbyyominame],
    [executecount],
    [failurecount],
    [failurepercent],
    [modifiedby],
    [modifiedbyname],
    [modifiedon],
    [modifiedonutc],
    [modifiedonbehalfby],
    [modifiedonbehalfbydsc],
    [modifiedonbehalfbyname],
    [modifiedonbehalfbyyominame],
    [organizationid],
    [plugintypeid],
    [plugintypeidname],
    [plugintypestatisticid],
    [terminatecpucontributionpercent],
    [terminatehandlescontributionpercent],
    [terminatememorycontributionpercent],
    [terminateothercontributionpercent]
) with view_metadata as
select
    [PluginTypeStatistic].[AverageExecuteTimeInMilliseconds],
    [PluginTypeStatistic].[CrashContributionPercent],
    [PluginTypeStatistic].[CrashCount],
    [PluginTypeStatistic].[CrashPercent],
    [PluginTypeStatistic].[CreatedBy],
    [PluginTypeStatistic].[CreatedByName],
    dbo.fn_UTCToTzSpecificLocalTime([PluginTypeStatistic].[CreatedOn], 
			us.TimeZoneBias,
			us.TimeZoneDaylightBias,
			us.TimeZoneDaylightYear,
			us.TimeZoneDaylightMonth,
			us.TimeZoneDaylightDay,
			us.TimeZoneDaylightHour,
			us.TimeZoneDaylightMinute,
			us.TimeZoneDaylightSecond,
			0,
			us.TimeZoneDaylightDayOfWeek,
			us.TimeZoneStandardBias,
			us.TimeZoneStandardYear,
			us.TimeZoneStandardMonth,
			us.TimeZoneStandardDay,
			us.TimeZoneStandardHour,
			us.TimeZoneStandardMinute,
			us.TimeZoneStandardSecond,
			0,
			us.TimeZoneStandardDayOfWeek),
        [PluginTypeStatistic].[CreatedOn],
    [PluginTypeStatistic].[CreatedOnBehalfBy],
    --[PluginTypeStatistic].[CreatedOnBehalfByDsc]
    0,
    [PluginTypeStatistic].[CreatedOnBehalfByName],
    [PluginTypeStatistic].[CreatedOnBehalfByYomiName],
    [PluginTypeStatistic].[ExecuteCount],
    [PluginTypeStatistic].[FailureCount],
    [PluginTypeStatistic].[FailurePercent],
    [PluginTypeStatistic].[ModifiedBy],
    [PluginTypeStatistic].[ModifiedByName],
    dbo.fn_UTCToTzSpecificLocalTime([PluginTypeStatistic].[ModifiedOn], 
			us.TimeZoneBias,
			us.TimeZoneDaylightBias,
			us.TimeZoneDaylightYear,
			us.TimeZoneDaylightMonth,
			us.TimeZoneDaylightDay,
			us.TimeZoneDaylightHour,
			us.TimeZoneDaylightMinute,
			us.TimeZoneDaylightSecond,
			0,
			us.TimeZoneDaylightDayOfWeek,
			us.TimeZoneStandardBias,
			us.TimeZoneStandardYear,
			us.TimeZoneStandardMonth,
			us.TimeZoneStandardDay,
			us.TimeZoneStandardHour,
			us.TimeZoneStandardMinute,
			us.TimeZoneStandardSecond,
			0,
			us.TimeZoneStandardDayOfWeek),
        [PluginTypeStatistic].[ModifiedOn],
    [PluginTypeStatistic].[ModifiedOnBehalfBy],
    --[PluginTypeStatistic].[ModifiedOnBehalfByDsc]
    0,
    [PluginTypeStatistic].[ModifiedOnBehalfByName],
    [PluginTypeStatistic].[ModifiedOnBehalfByYomiName],
    [PluginTypeStatistic].[OrganizationId],
    [PluginTypeStatistic].[PluginTypeId],
    [PluginTypeStatistic].[PluginTypeIdName],
    [PluginTypeStatistic].[PluginTypeStatisticId],
    [PluginTypeStatistic].[TerminateCpuContributionPercent],
    [PluginTypeStatistic].[TerminateHandlesContributionPercent],
    [PluginTypeStatistic].[TerminateMemoryContributionPercent],
    [PluginTypeStatistic].[TerminateOtherContributionPercent]
from PluginTypeStatistic
    join SystemUserBase u on (u.SystemUserId = dbo.fn_FindUserGuid() and u.IsDisabled = 0)
    left join UserSettingsBase us on us.SystemUserId = u.SystemUserId
    cross join dbo.fn_GetMaxPrivilegeDepthMask(4603) pdm
where
(
    -- privilege check
    pdm.PrivilegeDepthMask is not null and
    [PluginTypeStatistic].OrganizationId = u.OrganizationId
)
