CREATE ROLE [CRMReaderRole]
    AUTHORIZATION [dbo];


GO
ALTER ROLE [CRMReaderRole] ADD MEMBER [D1\PrivReportingGroup {a75c8b9a-e617-4daa-8593-5a4231fe7cb5}];


GO
ALTER ROLE [CRMReaderRole] ADD MEMBER [NT AUTHORITY\NETWORK SERVICE];

