


--
-- base view for Email
--
create view dbo.[Email]
 (
    -- logical attributes
    [cgi_email_recipient_IdName],
    [SenderMailboxIdName],
    [CreatedByYomiName],
    [cgi_cc_emailrecipientName],
    [CreatedOnBehalfByYomiName],
    [cgi_bcc_emailrecipientName],
    [ModifiedByYomiName],
    [ModifiedByName],
    [ModifiedOnBehalfByYomiName],
    [CreatedByName],
    [ModifiedOnBehalfByName],
    [TransactionCurrencyIdName],
    [ParentActivityIdName],
    [CreatedOnBehalfByName],

    -- ownership entries
    OwnerId,
    OwnerIdName,
    OwnerIdYomiName,
    OwnerIdDsc,
    OwnerIdType,
    OwningUser,
    OwningTeam,

    -- physical attributes
    [ScheduledStart],
    [StatusCode],
    [SubmittedBy],
    [Description],
    [IsWorkflowCreated],
    [ActivityId],
    [ScheduledEnd],
    [MimeType],
    [CreatedBy],
    [VersionNumber],
    [ReadReceiptRequested],
    [Subcategory],
    [IsBilled],
    [ActualDurationMinutes],
    [PriorityCode],
    [ModifiedBy],
    [ActualStart],
    [DirectionCode],
    [ActualEnd],
    [TrackingToken],
    [ServiceId],
    [ScheduledDurationMinutes],
    [Category],
    [CreatedOn],
    [OwningBusinessUnit],
    [Sender],
    [Subject],
    [ModifiedOn],
    [ToRecipients],
    [DeliveryReceiptRequested],
    [RegardingObjectId],
    [StateCode],
    [MessageId],
    [RegardingObjectTypeCode],
    [RegardingObjectIdName],
    [OverriddenCreatedOn],
    [ImportSequenceNumber],
    [DeliveryAttempts],
    [MessageIdDupCheck],
    [Compressed],
    [Notifications],
    [TimeZoneRuleVersionNumber],
    [UTCConversionTimeZoneCode],
    [RegardingObjectIdYomiName],
    [CreatedOnBehalfBy],
    [ModifiedOnBehalfBy],
    [ActivityTypeCode],
    [IsRegularActivity],
    [TransactionCurrencyId],
    [ExchangeRate],
    [EmailSender],
    [EmailSenderName],
    [EmailSenderObjectTypeCode],
    [SendersAccount],
    [SendersAccountObjectTypeCode],
    [AttachmentCount],
    [SenderMailboxId],
    [DeliveryPriorityCode],
    [ParentActivityId],
    [InReplyTo],
    [BaseConversationIndexHash],
    [ConversationIndex],
    [CorrelationMethod],
    [SentOn],
    [PostponeEmailProcessingUntil],
    [ProcessId],
    [StageId],
    [SendersAccountName],
    [SendersAccountYomiName],
    [EmailSenderYomiName],
    [cgi_Attention],
    [cgi_Remittance],
    [cgi_ask_customer],
    [cgi_email_recipient_Id],
    [cgi_button_customer],
    [cgi_cc_emailrecipient],
    [cgi_bcc_emailrecipient],
    [cgi_SourceType],
    [cgi_Type],
    [cgi_getfilelink]
) with view_metadata as
select
    -- logical attributes
    [cgi_emailrecipient_email].[cgi_emailrecipientname],
    [email_sendermailboxid_mailbox].[Name],
    [lk_email_createdby].[YomiFullName],
    [cgi_cgi_emailrecipient_email_cc_emailrecipient].[cgi_emailrecipientname],
    [lk_email_createdonbehalfby].[YomiFullName],
    [cgi_cgi_emailrecipient_email_bcc_emailrecipient].[cgi_emailrecipientname],
    [lk_email_modifiedby].[YomiFullName],
    [lk_email_modifiedby].[FullName],
    [lk_email_modifiedonbehalfby].[YomiFullName],
    [lk_email_createdby].[FullName],
    [lk_email_modifiedonbehalfby].[FullName],
    [TransactionCurrency_Email].[CurrencyName],
    [email_email_parentactivityid].[Subject],
    [lk_email_createdonbehalfby].[FullName],

    -- ownership entries
    OwnerId = [ActivityPointerBase].OwnerId,
    OwnerName = XXowner.Name,
    OwnerYomiName =  XXowner.YomiName,
    OwnerDsc = 0, -- DSC is removed, stub it to 0
    OwnerIdType = XXowner.OwnerIdType,
    OwningUser = case 
 		when XXowner.OwnerIdType= 8 then XXowner.OwnerId
		else null
		end,
    OwningTeam = case 
 		when XXowner.OwnerIdType= 9 then XXowner.OwnerId
		else null
		end,

    -- physical attribute
    [ActivityPointerBase].[ScheduledStart],
    [ActivityPointerBase].[StatusCode],
    [ActivityPointerBase].[SubmittedBy],
    [ActivityPointerBase].[Description],
    [ActivityPointerBase].[IsWorkflowCreated],
    [ActivityPointerBase].[ActivityId],
    [ActivityPointerBase].[ScheduledEnd],
    [ActivityPointerBase].[MimeType],
    [ActivityPointerBase].[CreatedBy],
    [ActivityPointerBase].[VersionNumber],
    [ActivityPointerBase].[ReadReceiptRequested],
    [ActivityPointerBase].[EmailSubcategory],
    [ActivityPointerBase].[IsBilled],
    [ActivityPointerBase].[ActualDurationMinutes],
    [ActivityPointerBase].[PriorityCode],
    [ActivityPointerBase].[ModifiedBy],
    [ActivityPointerBase].[ActualStart],
    [ActivityPointerBase].[EmailDirectionCode],
    [ActivityPointerBase].[ActualEnd],
    [ActivityPointerBase].[TrackingToken],
    [ActivityPointerBase].[ServiceId],
    [ActivityPointerBase].[ScheduledDurationMinutes],
    [ActivityPointerBase].[EmailCategory],
    [ActivityPointerBase].[CreatedOn],
    [ActivityPointerBase].[OwningBusinessUnit],
    [ActivityPointerBase].[Sender],
    [ActivityPointerBase].[Subject],
    [ActivityPointerBase].[ModifiedOn],
    [ActivityPointerBase].[ToRecipients],
    [ActivityPointerBase].[DeliveryReceiptRequested],
    [ActivityPointerBase].[RegardingObjectId],
    [ActivityPointerBase].[StateCode],
    [ActivityPointerBase].[MessageId],
    [ActivityPointerBase].[RegardingObjectTypeCode],
    [ActivityPointerBase].[RegardingObjectIdName],
    [ActivityPointerBase].[EmailOverriddenCreatedOn],
    [ActivityPointerBase].[EmailImportSequenceNumber],
    [ActivityPointerBase].[DeliveryAttempts],
    [ActivityPointerBase].[MessageIdDupCheck],
    [ActivityPointerBase].[Compressed],
    [ActivityPointerBase].[Notifications],
    [ActivityPointerBase].[TimeZoneRuleVersionNumber],
    [ActivityPointerBase].[UTCConversionTimeZoneCode],
    [ActivityPointerBase].[RegardingObjectIdYomiName],
    [ActivityPointerBase].[CreatedOnBehalfBy],
    [ActivityPointerBase].[ModifiedOnBehalfBy],
    [ActivityPointerBase].[ActivityTypeCode],
    [ActivityPointerBase].[IsRegularActivity],
    [ActivityPointerBase].[TransactionCurrencyId],
    [ActivityPointerBase].[ExchangeRate],
    [ActivityPointerBase].[EmailSender],
    [ActivityPointerBase].[EmailSenderName],
    [ActivityPointerBase].[EmailSenderObjectTypeCode],
    [ActivityPointerBase].[SendersAccount],
    [ActivityPointerBase].[SendersAccountObjectTypeCode],
    [ActivityPointerBase].[EmailAttachmentCount],
    [ActivityPointerBase].[SenderMailboxId],
    [ActivityPointerBase].[DeliveryPriorityCode],
    [ActivityPointerBase].[ParentActivityId],
    [ActivityPointerBase].[InReplyTo],
    [ActivityPointerBase].[BaseConversationIndexHash],
    [ActivityPointerBase].[ConversationIndex],
    [ActivityPointerBase].[CorrelationMethod],
    [ActivityPointerBase].[SentOn],
    [ActivityPointerBase].[PostponeActivityProcessingUntil],
    [ActivityPointerBase].[ProcessId],
    [ActivityPointerBase].[StageId],
    [ActivityPointerBase].[SendersAccountName],
    [ActivityPointerBase].[SendersAccountYomiName],
    [ActivityPointerBase].[EmailSenderYomiName],
    [EmailBase].[cgi_Attention],
    [EmailBase].[cgi_Remittance],
    [EmailBase].[cgi_ask_customer],
    [EmailBase].[cgi_email_recipient_Id],
    [EmailBase].[cgi_button_customer],
    [EmailBase].[cgi_cc_emailrecipient],
    [EmailBase].[cgi_bcc_emailrecipient],
    [EmailBase].[cgi_SourceType],
    [EmailBase].[cgi_Type],
    [EmailBase].[cgi_getfilelink]
from [ActivityPointerBase] 
    inner join [EmailBase] on ([ActivityPointerBase].[ActivityId] = [EmailBase].[ActivityId] and [ActivityPointerBase].[ActivityTypeCode] = 4202)
    left join [cgi_emailrecipientBase] [cgi_cgi_emailrecipient_email_bcc_emailrecipient] on ([EmailBase].[cgi_bcc_emailrecipient] = [cgi_cgi_emailrecipient_email_bcc_emailrecipient].[cgi_emailrecipientId])
    left join [cgi_emailrecipientBase] [cgi_cgi_emailrecipient_email_cc_emailrecipient] on ([EmailBase].[cgi_cc_emailrecipient] = [cgi_cgi_emailrecipient_email_cc_emailrecipient].[cgi_emailrecipientId])
    left join [cgi_emailrecipientBase] [cgi_emailrecipient_email] on ([EmailBase].[cgi_email_recipient_Id] = [cgi_emailrecipient_email].[cgi_emailrecipientId])
    left join [ActivityPointerBase] [email_email_parentactivityid] on ([ActivityPointerBase].[ParentActivityId] = [email_email_parentactivityid].[ActivityId] and [email_email_parentactivityid].[ActivityTypeCode] = 4202)
    left join [MailboxBase] [email_sendermailboxid_mailbox] on ([ActivityPointerBase].[SenderMailboxId] = [email_sendermailboxid_mailbox].[MailboxId])
    left join [SystemUserBase] [lk_email_createdby] with(nolock) on ([ActivityPointerBase].[CreatedBy] = [lk_email_createdby].[SystemUserId])
    left join [SystemUserBase] [lk_email_createdonbehalfby] with(nolock) on ([ActivityPointerBase].[CreatedOnBehalfBy] = [lk_email_createdonbehalfby].[SystemUserId])
    left join [SystemUserBase] [lk_email_modifiedby] with(nolock) on ([ActivityPointerBase].[ModifiedBy] = [lk_email_modifiedby].[SystemUserId])
    left join [SystemUserBase] [lk_email_modifiedonbehalfby] with(nolock) on ([ActivityPointerBase].[ModifiedOnBehalfBy] = [lk_email_modifiedonbehalfby].[SystemUserId])
    left join [TransactionCurrencyBase] [TransactionCurrency_Email] on ([ActivityPointerBase].[TransactionCurrencyId] = [TransactionCurrency_Email].[TransactionCurrencyId])
    left join OwnerBase XXowner with(nolock) on ([ActivityPointerBase].OwnerId = XXowner.OwnerId)
where [ActivityPointerBase].[ActivityTypeCode] = 4202