


--
-- base view for Incident
--
create view dbo.[Incident]
 (
    -- logical attributes
    [ModifiedByYomiName],
    [ModifiedOnBehalfByYomiName],
    [ResponsibleContactIdName],
    [EntityImage_URL],
    [cgi_casdet_row4_cat2IdName],
    [PrimaryContactIdYomiName],
    [SubjectIdName],
    [cgi_UnderordnaderendenIdName],
    [CreatedOnBehalfByYomiName],
    [PrimaryContactIdName],
    [cgi_RefundReimbursementFormName],
    [cgi_ThirdpartyNameidYomiName],
    [ContractIdName],
    [CreatedByName],
    [cgi_RepresentatividName],
    [EntityImage],
    [KbArticleIdName],
    [cgi_refundtransportcompanyidYomiName],
    [cgi_casdet_row2_cat2IdName],
    [CreatedByYomiName],
    [cgi_casdet_row2_cat1IdName],
    [cgi_letter_templateIdName],
    [cgi_casdet_row1_cat2IdName],
    [cgi_ContactidName],
    [cgi_AccountidYomiName],
    [MasterIdName],
    [cgi_FacebookPostidName],
    [SLAInvokedIdName],
    [cgi_ThirdpartyNameidName],
    [cgi_casdet_row1_cat1IdName],
    [cgi_casdet_row4_cat1IdName],
    [cgi_OriginalCallguideCategoryName],
    [cgi_ChatidName],
    [SocialProfileIdName],
    [cgi_TravelCardidName],
    [cgi_refundtransportcompanyidName],
    [cgi_casdet_row3_cat3IdName],
    [cgi_casdet_row3_cat2IdName],
    [cgi_RefundTypesName],
    [NumberOfChildIncidents],
    [ContractDetailIdName],
    [CreatedOnBehalfByName],
    [cgi_casdet_row1_cat3IdName],
    [ModifiedByName],
    [ResponsibleContactIdYomiName],
    [cgi_casdet_row4_cat3IdName],
    [cgi_AccountidName],
    [cgi_casdet_row3_cat1IdName],
    [EntityImage_Timestamp],
    [ParentCaseIdName],
    [cgi_CallGuideInfoName],
    [cgi_TravelInformationLookupName],
    [TransactionCurrencyIdName],
    [ModifiedOnBehalfByName],
    [cgi_casdet_row2_cat3IdName],
    [ProductIdName],
    [cgi_ContactidYomiName],
    [EntitlementIdName],

    -- ownership entries
    OwnerId,
    OwnerIdName,
    OwnerIdYomiName,
    OwnerIdDsc,
    OwnerIdType,
    OwningUser,
    OwningTeam,


	[AccountId],
	[AccountIdName],
	[AccountIdYomiName],
	[ContactId],
	[ContactIdName],
	[ContactIdYomiName],
    -- physical attributes
    [IncidentId],
    [OwningBusinessUnit],
    [ContractDetailId],
    [SubjectId],
    [ContractId],
    [ActualServiceUnits],
    [CaseOriginCode],
    [BilledServiceUnits],
    [CaseTypeCode],
    [ProductSerialNumber],
    [Title],
    [ProductId],
    [ContractServiceLevelCode],
    [Description],
    [IsDecrementing],
    [CreatedOn],
    [TicketNumber],
    [PriorityCode],
    [CustomerSatisfactionCode],
    [IncidentStageCode],
    [ModifiedOn],
    [CreatedBy],
    [FollowupBy],
    [ModifiedBy],
    [VersionNumber],
    [StateCode],
    [SeverityCode],
    [StatusCode],
    [ResponsibleContactId],
    [CustomerId],
    [CustomerIdName],
    [CustomerIdType],
    [KbArticleId],
    [TimeZoneRuleVersionNumber],
    [ImportSequenceNumber],
    [UTCConversionTimeZoneCode],
    [OverriddenCreatedOn],
    [CustomerIdYomiName],
    [CreatedOnBehalfBy],
    [ModifiedOnBehalfBy],
    [TransactionCurrencyId],
    [ExchangeRate],
    [ServiceStage],
    [ExistingCase],
    [StageId],
    [ProcessId],
    [EntityImageId],
    [CheckEmail],
    [ActivitiesComplete],
    [FollowUpTaskCreated],
    [SocialProfileId],
    [SLAInvokedId],
    [MessageTypeCode],
    [BlockedProfile],
    [EntitlementId],
    [MasterId],
    [ParentCaseId],
    [SentimentValue],
    [InfluenceScore],
    [Merged],
    [RouteCase],
    [ResolveBy],
    [ResponseBy],
    [CustomerContacted],
    [IsEscalated],
    [EscalatedOn],
    [PrimaryContactId],
    [FirstResponseSent],
    [FirstResponseSLAStatus],
    [ResolveBySLAStatus],
    [cgi_AccountNumber],
    [cgi_ChatConversation],
    [cgi_City],
    [cgi_ContactCustomer],
    [cgi_Country],
    [cgi_CustomerNumber],
    [cgi_CustomerPayout],
    [cgi_customerpayout_Base],
    [cgi_EmailAddress],
    [cgi_GiroNumber],
    [cgi_PaymentType],
    [cgi_Postaladdress],
    [cgi_SendMailAction],
    [cgi_StreetAddress],
    [cgi_TelephoneNumber],
    [cgi_Accountid],
    [cgi_Chatid],
    [cgi_FacebookPostid],
    [cgi_CallGuideInfo],
    [cgi_TravelCardid],
    [cgi_ThirdpartyNameid],
    [cgi_OriginalCallguideCategory],
    [cgi_ActionDate],
    [cgi_customer_email],
    [cgi_customer_telephonenumber],
    [cgi_case_category_selected],
    [cgi_set_anonymous_customer],
    [cgi_BOMBMobileNumber],
    [cgi_casdet_row1_cat1Id],
    [cgi_casdet_row1_cat2Id],
    [cgi_casdet_row1_cat3Id],
    [cgi_casdet_row2_cat1Id],
    [cgi_casdet_row2_cat2Id],
    [cgi_casdet_row2_cat3Id],
    [cgi_casdet_row3_cat2Id],
    [cgi_casdet_row3_cat1Id],
    [cgi_casdet_row3_cat3Id],
    [cgi_casdet_row4_cat1Id],
    [cgi_casdet_row4_cat2Id],
    [cgi_casdet_row4_cat3Id],
    [cgi_clearingnr],
    [cgi_customer_number],
    [cgi_soc_sec_number],
    [cgi_track_token],
    [cgi_sendtoqueue],
    [cgi_invoiceno],
    [cgi_controlfeeno],
    [cgi_way_of_transport],
    [cgi_line],
    [cgi_train],
    [cgi_county],
    [cgi_Contactid],
    [cgi_Customers_Category],
    [cgi_Customers_SubCategory],
    [cgi_CaseSolved],
    [cgi_emailcount],
    [cgi_sFN],
    [cgi_sLN],
    [cgi_sA],
    [cgi_sPA],
    [cgi_sPH],
    [cgi_sPW],
    [cgi_sPM],
    [cgi_sPF],
    [cgi_sEM],
    [cgi_sSSN],
    [cgi_sPR],
    [cgi_sOP1],
    [cgi_sOP2],
    [cgi_sTTJ],
    [cgi_iBID],
    [cgi_iDC],
    [cgi_TravelCardNo],
    [cgi_Representativid],
    [cgi_customer_demand],
    [cgi_arrival_date],
    [cgi_customer_telephonenumber_work],
    [cgi_customer_telephonenumber_mobile],
    [cgi_UnregisterdTravelCard],
    [cgi_case_remittance],
    [cgi_track_token_customer],
    [cgi_case_reopen],
    [cgi_letter_templateId],
    [cgi_letter_title],
    [cgi_letter_body],
    [cgi_RGOLIssueId],
    [cgi_DepartureDateTime],
    [cgi_full_name],
    [cgi_passhasbeenopenedatleastonce],
    [cgi_TravelInformation],
    [cgi_TravelInformationLookup],
    [cgi_TravelInformationCity],
    [cgi_TravelInformationLine],
    [cgi_TravelInformationTour],
    [cgi_TravelInformationCompany],
    [cgi_TravelInformationStart],
    [cgi_TravelInformationStop],
    [cgi_TravelInformationStartPlanned],
    [cgi_TravelInformationArrivalPlanned],
    [cgi_TravelInformationDirectionText],
    [cgi_TravelInformationDeviationMessage],
    [cgi_TravelInformationArrivalActual],
    [cgi_TravelInformationStartActual],
    [cgi_TravelInformationDisplayText],
    [cgi_TravelInformationTransport],
    [cgi_RunPriorityWorkflow],
    [cgi_UnderordnaderendenId],
    [cgi_RefundTypes],
    [cgi_RefundMilagekm],
    [cgi_RefundMilageCompensation],
    [cgi_RefundQuantity],
    [cgi_RefundCalculatedAmount],
    [cgi_RefundAmount],
    [cgi_refundamount_Base],
    [cgi_RefundReimbursementForm],
    [cgi_RefundValueCode],
    [cgi_RefundTravelCardNo],
    [cgi_RefundLastValid],
    [cgi_RefundAccountNo],
    [cgi_notravelinfo],
    [cgi_refundtransportcompanyid],
    [cgi_refundcomments],
    [cgi_refundcheckno],
    [cgi_CirculationNameInPass1],
    [cgi_CirculationNameInPass2],
    [cgi_OperatorPass1],
    [cgi_OperatorPass2],
    [cgi_refundmobilenumber],
    [cgi_remiss_emailreminders],
    [cgi_track_token_remiss_reminder],
    [cgi_Handelsedatum],
    [cgi_experienceddelay],
    [cgi_tickettype_1],
    [cgi_ticketnumber1],
    [cgi_tickettype_2],
    [cgi_ticketnumber2],
    [cgi_milagefrom],
    [cgi_milageto],
    [cgi_milagekilometers],
    [cgi_milagelicenseplatenumber],
    [cgi_taxifrom],
    [cgi_taxito],
    [cgi_compensationclaimfromrgol],
    [cgi_compensationclaimfromrgol_Base],
    [cgi_rgolcaselog],
    [cgi_reqreceipt],
    [cgi_iscompleted],
    [cgi_taxiclaimedamount],
    [cgi_taxiclaimedamount_Base],
    [cgi_refundapprovaltype],
    [cgi_iban],
    [cgi_bic],
    [cgi_description2],
    [cgi_rgol_socialsecuritynumber],
    [cgi_rgol_telephonenumber],
    [cgi_rgol_fullname],
    [cgi_rgol_address1_line1],
    [cgi_rgol_address1_line2],
    [cgi_rgol_address1_postalcode],
    [cgi_rgol_address1_city],
    [cgi_rgol_address1_country],
    [cgi_rgol_delivery_email]
) with view_metadata as
select
    -- logical attributes
    [lk_incidentbase_modifiedby].[YomiFullName],
    [lk_incidentbase_modifiedonbehalfby].[YomiFullName],
    [contact_as_responsible_contact].[FullName],
    [lk_incident_entityimage].[ImageURL],
    [cgi_4_2_categorydetail_incident].[cgi_categorydetailname],
    [contact_as_primary_contact].[YomiFullName],
    [subject_incidents].[Title],
    [cgi_incident_incident].[Title],
    [lk_incidentbase_createdonbehalfby].[YomiFullName],
    [contact_as_primary_contact].[FullName],
    [cgi_cgi_reimbursementform_incident_RefundReimbursementForm].[cgi_reimbursementname],
    [cgi_contact_incident_ThirdpartyNameid].[YomiFullName],
    [contract_cases].[Title],
    [lk_incidentbase_createdby].[FullName],
    [cgi_cgi_representative_incident_Representativid].[cgi_name],
    [lk_incident_entityimage].[ImageData],
    [kbarticle_incidents].[Title],
    [cgi_account_incident_RefundTransportCompanyId].[YomiName],
    [cgi_2_2_categorydetail_incident].[cgi_categorydetailname],
    [lk_incidentbase_createdby].[YomiFullName],
    [cgi_2_1_categorydetail_incident].[cgi_categorydetailname],
    [cgi_letter_template_incident].[cgi_name],
    [cgi_1_2_categorydetail_incident].[cgi_categorydetailname],
    [cgi_contact_incident_Contactid].[FullName],
    [cgi_account_incident_Account].[YomiName],
    [incident_master_incident].[Title],
    [cgi_cgi_callguidefacebook_incident_FacebookPostid].[Subject],
    [sla_cases].[Name],
    [cgi_contact_incident_ThirdpartyNameid].[FullName],
    [cgi_1_1_categorydetail_incident].[cgi_categorydetailname],
    [cgi_4_1_categorydetail_incident].[cgi_categorydetailname],
    [cgi_cgi_categorydetail_incident_OriginalCallguideCategory].[cgi_categorydetailname],
    [cgi_cgi_callguidechat_incident_Chatid].[Subject],
    [socialprofile_cases].[ProfileName],
    [cgi_cgi_travelcard_incident_TravelCardid].[cgi_travelcardnumber],
    [cgi_account_incident_RefundTransportCompanyId].[Name],
    [cgi_3_3_categorydetail_incident].[cgi_categorydetailname],
    [cgi_3_2_categorydetail_incident].[cgi_categorydetailname],
    [cgi_cgi_refundtype_incident_RefundTypes].[cgi_refundtypename],
    [lk_incident_ChildIncidentCount].[NumberOfChildIncidents],
    [contract_detail_cases].[Title],
    [lk_incidentbase_createdonbehalfby].[FullName],
    [cgi_1_3_categorydetail_incident].[cgi_categorydetailname],
    [lk_incidentbase_modifiedby].[FullName],
    [contact_as_responsible_contact].[YomiFullName],
    [cgi_4_3_categorydetail_incident].[cgi_categorydetailname],
    [cgi_account_incident_Account].[Name],
    [cgi_3_1_categorydetail_incident].[cgi_categorydetailname],
    [lk_incident_entityimage].[ImageTimestamp],
    [incident_parent_incident].[Title],
    [cgi_cgi_callguideinfo_incident_CallGuideInfo].[cgi_callguideinfoname],
    [cgi_cgi_travelinformation_incident_TravelInformation].[cgi_travelinformation],
    [TransactionCurrency_Incident].[CurrencyName],
    [lk_incidentbase_modifiedonbehalfby].[FullName],
    [cgi_2_3_categorydetail_incident].[cgi_categorydetailname],
    [product_incidents].[Name],
    [cgi_contact_incident_Contactid].[YomiFullName],
    [entitlement_cases].[Name],

    -- ownership entries
    OwnerId = [IncidentBase].OwnerId,
    OwnerName = XXowner.Name,
    OwnerYomiName =  XXowner.YomiName,
    OwnerDsc = 0, -- DSC is removed, stub it to 0
    OwnerIdType = XXowner.OwnerIdType,
    OwningUser = case 
 		when XXowner.OwnerIdType= 8 then XXowner.OwnerId
		else null
		end,
    OwningTeam = case 
 		when XXowner.OwnerIdType= 9 then XXowner.OwnerId
		else null
		end,


	[AccountId] = case 
		when [IncidentBase].[CustomerIdType] = 1 AND [IncidentBase].[CustomerId] IS NOT NULL then [IncidentBase].[CustomerId]
		else NULL
		end,
	[AccountIdName] = case 
		when [IncidentBase].[CustomerIdType] = 1 AND [IncidentBase].[CustomerId] IS NOT NULL then [IncidentBase].[CustomerIdName]
		else NULL
		end,
	[AccountIdYomiName] = case 
		when [IncidentBase].[CustomerIdType] = 1 AND [IncidentBase].[CustomerId] IS NOT NULL then [IncidentBase].[CustomerIdYomiName]
		else NULL
		end,
	[ContactId] = case 
		when [IncidentBase].[CustomerIdType] = 2 AND [IncidentBase].[CustomerId] IS NOT NULL then [IncidentBase].[CustomerId]
		else NULL
		end,
	[ContactIdName] = case 
		when [IncidentBase].[CustomerIdType] = 2 AND [IncidentBase].[CustomerId] IS NOT NULL then [IncidentBase].[CustomerIdName]
		else NULL
		end,
	[ContactIdYomiName] = case 
		when [IncidentBase].[CustomerIdType] = 2 AND [IncidentBase].[CustomerId] IS NOT NULL then [IncidentBase].[CustomerIdYomiName]
		else NULL
		end,
    -- physical attribute
    [IncidentBase].[IncidentId],
    [IncidentBase].[OwningBusinessUnit],
    [IncidentBase].[ContractDetailId],
    [IncidentBase].[SubjectId],
    [IncidentBase].[ContractId],
    [IncidentBase].[ActualServiceUnits],
    [IncidentBase].[CaseOriginCode],
    [IncidentBase].[BilledServiceUnits],
    [IncidentBase].[CaseTypeCode],
    [IncidentBase].[ProductSerialNumber],
    [IncidentBase].[Title],
    [IncidentBase].[ProductId],
    [IncidentBase].[ContractServiceLevelCode],
    [IncidentBase].[Description],
    [IncidentBase].[IsDecrementing],
    [IncidentBase].[CreatedOn],
    [IncidentBase].[TicketNumber],
    [IncidentBase].[PriorityCode],
    [IncidentBase].[CustomerSatisfactionCode],
    [IncidentBase].[IncidentStageCode],
    [IncidentBase].[ModifiedOn],
    [IncidentBase].[CreatedBy],
    [IncidentBase].[FollowupBy],
    [IncidentBase].[ModifiedBy],
    [IncidentBase].[VersionNumber],
    [IncidentBase].[StateCode],
    [IncidentBase].[SeverityCode],
    [IncidentBase].[StatusCode],
    [IncidentBase].[ResponsibleContactId],
    [IncidentBase].[CustomerId],
    [IncidentBase].[CustomerIdName],
    [IncidentBase].[CustomerIdType],
    [IncidentBase].[KbArticleId],
    [IncidentBase].[TimeZoneRuleVersionNumber],
    [IncidentBase].[ImportSequenceNumber],
    [IncidentBase].[UTCConversionTimeZoneCode],
    [IncidentBase].[OverriddenCreatedOn],
    [IncidentBase].[CustomerIdYomiName],
    [IncidentBase].[CreatedOnBehalfBy],
    [IncidentBase].[ModifiedOnBehalfBy],
    [IncidentBase].[TransactionCurrencyId],
    [IncidentBase].[ExchangeRate],
    [IncidentBase].[ServiceStage],
    [IncidentBase].[ExistingCase],
    [IncidentBase].[StageId],
    [IncidentBase].[ProcessId],
    [IncidentBase].[EntityImageId],
    [IncidentBase].[CheckEmail],
    [IncidentBase].[ActivitiesComplete],
    [IncidentBase].[FollowUpTaskCreated],
    [IncidentBase].[SocialProfileId],
    [IncidentBase].[SLAInvokedId],
    [IncidentBase].[MessageTypeCode],
    [IncidentBase].[BlockedProfile],
    [IncidentBase].[EntitlementId],
    [IncidentBase].[MasterId],
    [IncidentBase].[ParentCaseId],
    [IncidentBase].[SentimentValue],
    [IncidentBase].[InfluenceScore],
    [IncidentBase].[Merged],
    [IncidentBase].[RouteCase],
    [IncidentBase].[ResolveBy],
    [IncidentBase].[ResponseBy],
    [IncidentBase].[CustomerContacted],
    [IncidentBase].[IsEscalated],
    [IncidentBase].[EscalatedOn],
    [IncidentBase].[PrimaryContactId],
    [IncidentBase].[FirstResponseSent],
    [IncidentBase].[FirstResponseSLAStatus],
    [IncidentBase].[ResolveBySLAStatus],
    [IncidentBase].[cgi_AccountNumber],
    [IncidentBase].[cgi_ChatConversation],
    [IncidentBase].[cgi_City],
    [IncidentBase].[cgi_ContactCustomer],
    [IncidentBase].[cgi_Country],
    [IncidentBase].[cgi_CustomerNumber],
    [IncidentBase].[cgi_CustomerPayout],
    [IncidentBase].[cgi_customerpayout_Base],
    [IncidentBase].[cgi_EmailAddress],
    [IncidentBase].[cgi_GiroNumber],
    [IncidentBase].[cgi_PaymentType],
    [IncidentBase].[cgi_Postaladdress],
    [IncidentBase].[cgi_SendMailAction],
    [IncidentBase].[cgi_StreetAddress],
    [IncidentBase].[cgi_TelephoneNumber],
    [IncidentBase].[cgi_Accountid],
    [IncidentBase].[cgi_Chatid],
    [IncidentBase].[cgi_FacebookPostid],
    [IncidentBase].[cgi_CallGuideInfo],
    [IncidentBase].[cgi_TravelCardid],
    [IncidentBase].[cgi_ThirdpartyNameid],
    [IncidentBase].[cgi_OriginalCallguideCategory],
    [IncidentBase].[cgi_ActionDate],
    [IncidentBase].[cgi_customer_email],
    [IncidentBase].[cgi_customer_telephonenumber],
    [IncidentBase].[cgi_case_category_selected],
    [IncidentBase].[cgi_set_anonymous_customer],
    [IncidentBase].[cgi_BOMBMobileNumber],
    [IncidentBase].[cgi_casdet_row1_cat1Id],
    [IncidentBase].[cgi_casdet_row1_cat2Id],
    [IncidentBase].[cgi_casdet_row1_cat3Id],
    [IncidentBase].[cgi_casdet_row2_cat1Id],
    [IncidentBase].[cgi_casdet_row2_cat2Id],
    [IncidentBase].[cgi_casdet_row2_cat3Id],
    [IncidentBase].[cgi_casdet_row3_cat2Id],
    [IncidentBase].[cgi_casdet_row3_cat1Id],
    [IncidentBase].[cgi_casdet_row3_cat3Id],
    [IncidentBase].[cgi_casdet_row4_cat1Id],
    [IncidentBase].[cgi_casdet_row4_cat2Id],
    [IncidentBase].[cgi_casdet_row4_cat3Id],
    [IncidentBase].[cgi_clearingnr],
    [IncidentBase].[cgi_customer_number],
    [IncidentBase].[cgi_soc_sec_number],
    [IncidentBase].[cgi_track_token],
    [IncidentBase].[cgi_sendtoqueue],
    [IncidentBase].[cgi_invoiceno],
    [IncidentBase].[cgi_controlfeeno],
    [IncidentBase].[cgi_way_of_transport],
    [IncidentBase].[cgi_line],
    [IncidentBase].[cgi_train],
    [IncidentBase].[cgi_county],
    [IncidentBase].[cgi_Contactid],
    [IncidentBase].[cgi_Customers_Category],
    [IncidentBase].[cgi_Customers_SubCategory],
    [IncidentBase].[cgi_CaseSolved],
    [IncidentBase].[cgi_emailcount],
    [IncidentBase].[cgi_sFN],
    [IncidentBase].[cgi_sLN],
    [IncidentBase].[cgi_sA],
    [IncidentBase].[cgi_sPA],
    [IncidentBase].[cgi_sPH],
    [IncidentBase].[cgi_sPW],
    [IncidentBase].[cgi_sPM],
    [IncidentBase].[cgi_sPF],
    [IncidentBase].[cgi_sEM],
    [IncidentBase].[cgi_sSSN],
    [IncidentBase].[cgi_sPR],
    [IncidentBase].[cgi_sOP1],
    [IncidentBase].[cgi_sOP2],
    [IncidentBase].[cgi_sTTJ],
    [IncidentBase].[cgi_iBID],
    [IncidentBase].[cgi_iDC],
    [IncidentBase].[cgi_TravelCardNo],
    [IncidentBase].[cgi_Representativid],
    [IncidentBase].[cgi_customer_demand],
    [IncidentBase].[cgi_arrival_date],
    [IncidentBase].[cgi_customer_telephonenumber_work],
    [IncidentBase].[cgi_customer_telephonenumber_mobile],
    [IncidentBase].[cgi_UnregisterdTravelCard],
    [IncidentBase].[cgi_case_remittance],
    [IncidentBase].[cgi_track_token_customer],
    [IncidentBase].[cgi_case_reopen],
    [IncidentBase].[cgi_letter_templateId],
    [IncidentBase].[cgi_letter_title],
    [IncidentBase].[cgi_letter_body],
    [IncidentBase].[cgi_RGOLIssueId],
    [IncidentBase].[cgi_DepartureDateTime],
    [IncidentBase].[cgi_full_name],
    [IncidentBase].[cgi_passhasbeenopenedatleastonce],
    [IncidentBase].[cgi_TravelInformation],
    [IncidentBase].[cgi_TravelInformationLookup],
    [IncidentBase].[cgi_TravelInformationCity],
    [IncidentBase].[cgi_TravelInformationLine],
    [IncidentBase].[cgi_TravelInformationTour],
    [IncidentBase].[cgi_TravelInformationCompany],
    [IncidentBase].[cgi_TravelInformationStart],
    [IncidentBase].[cgi_TravelInformationStop],
    [IncidentBase].[cgi_TravelInformationStartPlanned],
    [IncidentBase].[cgi_TravelInformationArrivalPlanned],
    [IncidentBase].[cgi_TravelInformationDirectionText],
    [IncidentBase].[cgi_TravelInformationDeviationMessage],
    [IncidentBase].[cgi_TravelInformationArrivalActual],
    [IncidentBase].[cgi_TravelInformationStartActual],
    [IncidentBase].[cgi_TravelInformationDisplayText],
    [IncidentBase].[cgi_TravelInformationTransport],
    [IncidentBase].[cgi_RunPriorityWorkflow],
    [IncidentBase].[cgi_UnderordnaderendenId],
    [IncidentBase].[cgi_RefundTypes],
    [IncidentBase].[cgi_RefundMilagekm],
    [IncidentBase].[cgi_RefundMilageCompensation],
    [IncidentBase].[cgi_RefundQuantity],
    [IncidentBase].[cgi_RefundCalculatedAmount],
    [IncidentBase].[cgi_RefundAmount],
    [IncidentBase].[cgi_refundamount_Base],
    [IncidentBase].[cgi_RefundReimbursementForm],
    [IncidentBase].[cgi_RefundValueCode],
    [IncidentBase].[cgi_RefundTravelCardNo],
    [IncidentBase].[cgi_RefundLastValid],
    [IncidentBase].[cgi_RefundAccountNo],
    [IncidentBase].[cgi_notravelinfo],
    [IncidentBase].[cgi_refundtransportcompanyid],
    [IncidentBase].[cgi_refundcomments],
    [IncidentBase].[cgi_refundcheckno],
    [IncidentBase].[cgi_CirculationNameInPass1],
    [IncidentBase].[cgi_CirculationNameInPass2],
    [IncidentBase].[cgi_OperatorPass1],
    [IncidentBase].[cgi_OperatorPass2],
    [IncidentBase].[cgi_refundmobilenumber],
    [IncidentBase].[cgi_remiss_emailreminders],
    [IncidentBase].[cgi_track_token_remiss_reminder],
    [IncidentBase].[cgi_Handelsedatum],
    [IncidentBase].[cgi_experienceddelay],
    [IncidentBase].[cgi_tickettype_1],
    [IncidentBase].[cgi_ticketnumber1],
    [IncidentBase].[cgi_tickettype_2],
    [IncidentBase].[cgi_ticketnumber2],
    [IncidentBase].[cgi_milagefrom],
    [IncidentBase].[cgi_milageto],
    [IncidentBase].[cgi_milagekilometers],
    [IncidentBase].[cgi_milagelicenseplatenumber],
    [IncidentBase].[cgi_taxifrom],
    [IncidentBase].[cgi_taxito],
    [IncidentBase].[cgi_compensationclaimfromrgol],
    [IncidentBase].[cgi_compensationclaimfromrgol_Base],
    [IncidentBase].[cgi_rgolcaselog],
    [IncidentBase].[cgi_reqreceipt],
    [IncidentBase].[cgi_iscompleted],
    [IncidentBase].[cgi_taxiclaimedamount],
    [IncidentBase].[cgi_taxiclaimedamount_Base],
    [IncidentBase].[cgi_refundapprovaltype],
    [IncidentBase].[cgi_iban],
    [IncidentBase].[cgi_bic],
    [IncidentBase].[cgi_description2],
    [IncidentBase].[cgi_rgol_socialsecuritynumber],
    [IncidentBase].[cgi_rgol_telephonenumber],
    [IncidentBase].[cgi_rgol_fullname],
    [IncidentBase].[cgi_rgol_address1_line1],
    [IncidentBase].[cgi_rgol_address1_line2],
    [IncidentBase].[cgi_rgol_address1_postalcode],
    [IncidentBase].[cgi_rgol_address1_city],
    [IncidentBase].[cgi_rgol_address1_country],
    [IncidentBase].[cgi_rgol_delivery_email]
from [IncidentBase] 
    left join [cgi_categorydetailBase] [cgi_1_1_categorydetail_incident] on ([IncidentBase].[cgi_casdet_row1_cat1Id] = [cgi_1_1_categorydetail_incident].[cgi_categorydetailId])
    left join [cgi_categorydetailBase] [cgi_1_2_categorydetail_incident] on ([IncidentBase].[cgi_casdet_row1_cat2Id] = [cgi_1_2_categorydetail_incident].[cgi_categorydetailId])
    left join [cgi_categorydetailBase] [cgi_1_3_categorydetail_incident] on ([IncidentBase].[cgi_casdet_row1_cat3Id] = [cgi_1_3_categorydetail_incident].[cgi_categorydetailId])
    left join [cgi_categorydetailBase] [cgi_2_1_categorydetail_incident] on ([IncidentBase].[cgi_casdet_row2_cat1Id] = [cgi_2_1_categorydetail_incident].[cgi_categorydetailId])
    left join [cgi_categorydetailBase] [cgi_2_2_categorydetail_incident] on ([IncidentBase].[cgi_casdet_row2_cat2Id] = [cgi_2_2_categorydetail_incident].[cgi_categorydetailId])
    left join [cgi_categorydetailBase] [cgi_2_3_categorydetail_incident] on ([IncidentBase].[cgi_casdet_row2_cat3Id] = [cgi_2_3_categorydetail_incident].[cgi_categorydetailId])
    left join [cgi_categorydetailBase] [cgi_3_1_categorydetail_incident] on ([IncidentBase].[cgi_casdet_row3_cat1Id] = [cgi_3_1_categorydetail_incident].[cgi_categorydetailId])
    left join [cgi_categorydetailBase] [cgi_3_2_categorydetail_incident] on ([IncidentBase].[cgi_casdet_row3_cat2Id] = [cgi_3_2_categorydetail_incident].[cgi_categorydetailId])
    left join [cgi_categorydetailBase] [cgi_3_3_categorydetail_incident] on ([IncidentBase].[cgi_casdet_row3_cat3Id] = [cgi_3_3_categorydetail_incident].[cgi_categorydetailId])
    left join [cgi_categorydetailBase] [cgi_4_1_categorydetail_incident] on ([IncidentBase].[cgi_casdet_row4_cat1Id] = [cgi_4_1_categorydetail_incident].[cgi_categorydetailId])
    left join [cgi_categorydetailBase] [cgi_4_2_categorydetail_incident] on ([IncidentBase].[cgi_casdet_row4_cat2Id] = [cgi_4_2_categorydetail_incident].[cgi_categorydetailId])
    left join [cgi_categorydetailBase] [cgi_4_3_categorydetail_incident] on ([IncidentBase].[cgi_casdet_row4_cat3Id] = [cgi_4_3_categorydetail_incident].[cgi_categorydetailId])
    left join [AccountBase] [cgi_account_incident_Account] on ([IncidentBase].[cgi_Accountid] = [cgi_account_incident_Account].[AccountId])
    left join [AccountBase] [cgi_account_incident_RefundTransportCompanyId] on ([IncidentBase].[cgi_refundtransportcompanyid] = [cgi_account_incident_RefundTransportCompanyId].[AccountId])
    left join [ActivityPointerBase] [cgi_cgi_callguidechat_incident_Chatid] on ([IncidentBase].[cgi_Chatid] = [cgi_cgi_callguidechat_incident_Chatid].[ActivityId] and [cgi_cgi_callguidechat_incident_Chatid].[ActivityTypeCode] = 10008)
    left join [ActivityPointerBase] [cgi_cgi_callguidefacebook_incident_FacebookPostid] on ([IncidentBase].[cgi_FacebookPostid] = [cgi_cgi_callguidefacebook_incident_FacebookPostid].[ActivityId] and [cgi_cgi_callguidefacebook_incident_FacebookPostid].[ActivityTypeCode] = 10009)
    left join [cgi_callguideinfoBase] [cgi_cgi_callguideinfo_incident_CallGuideInfo] on ([IncidentBase].[cgi_CallGuideInfo] = [cgi_cgi_callguideinfo_incident_CallGuideInfo].[cgi_callguideinfoId])
    left join [cgi_categorydetailBase] [cgi_cgi_categorydetail_incident_OriginalCallguideCategory] on ([IncidentBase].[cgi_OriginalCallguideCategory] = [cgi_cgi_categorydetail_incident_OriginalCallguideCategory].[cgi_categorydetailId])
    left join [cgi_refundtypeBase] [cgi_cgi_refundtype_incident_RefundTypes] on ([IncidentBase].[cgi_RefundTypes] = [cgi_cgi_refundtype_incident_RefundTypes].[cgi_refundtypeId])
    left join [cgi_reimbursementformBase] [cgi_cgi_reimbursementform_incident_RefundReimbursementForm] on ([IncidentBase].[cgi_RefundReimbursementForm] = [cgi_cgi_reimbursementform_incident_RefundReimbursementForm].[cgi_reimbursementformId])
    left join [cgi_representativeBase] [cgi_cgi_representative_incident_Representativid] on ([IncidentBase].[cgi_Representativid] = [cgi_cgi_representative_incident_Representativid].[cgi_representativeId])
    left join [cgi_travelcardBase] [cgi_cgi_travelcard_incident_TravelCardid] on ([IncidentBase].[cgi_TravelCardid] = [cgi_cgi_travelcard_incident_TravelCardid].[cgi_travelcardId])
    left join [cgi_travelinformationBase] [cgi_cgi_travelinformation_incident_TravelInformation] on ([IncidentBase].[cgi_TravelInformationLookup] = [cgi_cgi_travelinformation_incident_TravelInformation].[cgi_travelinformationId])
    left join [ContactBase] [cgi_contact_incident_Contactid] on ([IncidentBase].[cgi_Contactid] = [cgi_contact_incident_Contactid].[ContactId])
    left join [ContactBase] [cgi_contact_incident_ThirdpartyNameid] on ([IncidentBase].[cgi_ThirdpartyNameid] = [cgi_contact_incident_ThirdpartyNameid].[ContactId])
    left join [IncidentBase] [cgi_incident_incident] on ([IncidentBase].[cgi_UnderordnaderendenId] = [cgi_incident_incident].[IncidentId])
    left join [cgi_letter_templateBase] [cgi_letter_template_incident] on ([IncidentBase].[cgi_letter_templateId] = [cgi_letter_template_incident].[cgi_letter_templateId])
    left join [ContactBase] [contact_as_primary_contact] on ([IncidentBase].[PrimaryContactId] = [contact_as_primary_contact].[ContactId])
    left join [ContactBase] [contact_as_responsible_contact] on ([IncidentBase].[ResponsibleContactId] = [contact_as_responsible_contact].[ContactId])
    left join [ContractBase] [contract_cases] on ([IncidentBase].[ContractId] = [contract_cases].[ContractId])
    left join [ContractDetailBase] [contract_detail_cases] on ([IncidentBase].[ContractDetailId] = [contract_detail_cases].[ContractDetailId])
    left join [EntitlementBase] [entitlement_cases] on ([IncidentBase].[EntitlementId] = [entitlement_cases].[EntitlementId])
    left join [IncidentBase] [incident_master_incident] on ([IncidentBase].[MasterId] = [incident_master_incident].[IncidentId])
    left join [IncidentBase] [incident_parent_incident] on ([IncidentBase].[ParentCaseId] = [incident_parent_incident].[IncidentId])
    left join [KbArticleBase] [kbarticle_incidents] on ([IncidentBase].[KbArticleId] = [kbarticle_incidents].[KbArticleId])
    left join [ChildIncidentCount] [lk_incident_ChildIncidentCount] on ([IncidentBase].[IncidentId] = [lk_incident_ChildIncidentCount].[ParentCaseId])
    left join [ImageDescriptor] [lk_incident_entityimage] on ([IncidentBase].[EntityImageId] = [lk_incident_entityimage].[ImageDescriptorId])
    left join [SystemUserBase] [lk_incidentbase_createdby] with(nolock) on ([IncidentBase].[CreatedBy] = [lk_incidentbase_createdby].[SystemUserId])
    left join [SystemUserBase] [lk_incidentbase_createdonbehalfby] with(nolock) on ([IncidentBase].[CreatedOnBehalfBy] = [lk_incidentbase_createdonbehalfby].[SystemUserId])
    left join [SystemUserBase] [lk_incidentbase_modifiedby] with(nolock) on ([IncidentBase].[ModifiedBy] = [lk_incidentbase_modifiedby].[SystemUserId])
    left join [SystemUserBase] [lk_incidentbase_modifiedonbehalfby] with(nolock) on ([IncidentBase].[ModifiedOnBehalfBy] = [lk_incidentbase_modifiedonbehalfby].[SystemUserId])
    left join [ProductBase] [product_incidents] on ([IncidentBase].[ProductId] = [product_incidents].[ProductId])
    left join [SLABase] [sla_cases] on ([IncidentBase].[SLAInvokedId] = [sla_cases].[SLAId] and [sla_cases].OverwriteTime = 0 and [sla_cases].ComponentState = 0)
    left join [SocialProfileBase] [socialprofile_cases] on ([IncidentBase].[SocialProfileId] = [socialprofile_cases].[SocialProfileId])
    left join [SubjectBase] [subject_incidents] on ([IncidentBase].[SubjectId] = [subject_incidents].[SubjectId])
    left join [TransactionCurrencyBase] [TransactionCurrency_Incident] on ([IncidentBase].[TransactionCurrencyId] = [TransactionCurrency_Incident].[TransactionCurrencyId])
    left join OwnerBase XXowner with(nolock) on ([IncidentBase].OwnerId = XXowner.OwnerId)
