//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGIXrmExtConnectorService.SvcCallsForServiceJourney {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://INTSTDK001_PubTransRealTime", ConfigurationName="SvcCallsForServiceJourney.CallsForServiceJourney")]
    public interface CallsForServiceJourney {
        
        // CODEGEN: Generating message contract since the operation GetCallsForServiceJourney is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetCallsForServiceJourney", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CGIXrmExtConnectorService.SvcCallsForServiceJourney.GetCallsForServiceJourneyResponse GetCallsForServiceJourney(CGIXrmExtConnectorService.SvcCallsForServiceJourney.GetCallsForServiceJourneyRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.skanestrafiken.com/DK/INTSTDK001/GetCallsForServiceJourney/20141020")]
    public partial class GetCallsforServiceJourney : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string forServiceJourneyIdOrGidField;
        
        private System.DateTime atOperatingDateField;
        
        private bool atOperatingDateFieldSpecified;
        
        private string atStopGidField;
        
        private bool includeArrivalsTableField;
        
        private bool includeArrivalsTableFieldSpecified;
        
        private bool includeDeparturesTableField;
        
        private bool includeDeparturesTableFieldSpecified;
        
        private bool includeDeviationTablesField;
        
        private bool includeDeviationTablesFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string forServiceJourneyIdOrGid {
            get {
                return this.forServiceJourneyIdOrGidField;
            }
            set {
                this.forServiceJourneyIdOrGidField = value;
                this.RaisePropertyChanged("forServiceJourneyIdOrGid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime atOperatingDate {
            get {
                return this.atOperatingDateField;
            }
            set {
                this.atOperatingDateField = value;
                this.RaisePropertyChanged("atOperatingDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool atOperatingDateSpecified {
            get {
                return this.atOperatingDateFieldSpecified;
            }
            set {
                this.atOperatingDateFieldSpecified = value;
                this.RaisePropertyChanged("atOperatingDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string atStopGid {
            get {
                return this.atStopGidField;
            }
            set {
                this.atStopGidField = value;
                this.RaisePropertyChanged("atStopGid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool includeArrivalsTable {
            get {
                return this.includeArrivalsTableField;
            }
            set {
                this.includeArrivalsTableField = value;
                this.RaisePropertyChanged("includeArrivalsTable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool includeArrivalsTableSpecified {
            get {
                return this.includeArrivalsTableFieldSpecified;
            }
            set {
                this.includeArrivalsTableFieldSpecified = value;
                this.RaisePropertyChanged("includeArrivalsTableSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool includeDeparturesTable {
            get {
                return this.includeDeparturesTableField;
            }
            set {
                this.includeDeparturesTableField = value;
                this.RaisePropertyChanged("includeDeparturesTable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool includeDeparturesTableSpecified {
            get {
                return this.includeDeparturesTableFieldSpecified;
            }
            set {
                this.includeDeparturesTableFieldSpecified = value;
                this.RaisePropertyChanged("includeDeparturesTableSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool includeDeviationTables {
            get {
                return this.includeDeviationTablesField;
            }
            set {
                this.includeDeviationTablesField = value;
                this.RaisePropertyChanged("includeDeviationTables");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool includeDeviationTablesSpecified {
            get {
                return this.includeDeviationTablesFieldSpecified;
            }
            set {
                this.includeDeviationTablesFieldSpecified = value;
                this.RaisePropertyChanged("includeDeviationTablesSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetCallsforServiceJourneyMethodArrivalDeviation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal idField;
        
        private bool idFieldSpecified;
        
        private decimal isOnArrivalIdField;
        
        private bool isOnArrivalIdFieldSpecified;
        
        private bool affectsPreviousDeparturesYesNoField;
        
        private bool affectsPreviousDeparturesYesNoFieldSpecified;
        
        private decimal hasDeviationMessageVersionIdField;
        
        private bool hasDeviationMessageVersionIdFieldSpecified;
        
        private string consequenceLongCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal IsOnArrivalId {
            get {
                return this.isOnArrivalIdField;
            }
            set {
                this.isOnArrivalIdField = value;
                this.RaisePropertyChanged("IsOnArrivalId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsOnArrivalIdSpecified {
            get {
                return this.isOnArrivalIdFieldSpecified;
            }
            set {
                this.isOnArrivalIdFieldSpecified = value;
                this.RaisePropertyChanged("IsOnArrivalIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool AffectsPreviousDeparturesYesNo {
            get {
                return this.affectsPreviousDeparturesYesNoField;
            }
            set {
                this.affectsPreviousDeparturesYesNoField = value;
                this.RaisePropertyChanged("AffectsPreviousDeparturesYesNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AffectsPreviousDeparturesYesNoSpecified {
            get {
                return this.affectsPreviousDeparturesYesNoFieldSpecified;
            }
            set {
                this.affectsPreviousDeparturesYesNoFieldSpecified = value;
                this.RaisePropertyChanged("AffectsPreviousDeparturesYesNoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal HasDeviationMessageVersionId {
            get {
                return this.hasDeviationMessageVersionIdField;
            }
            set {
                this.hasDeviationMessageVersionIdField = value;
                this.RaisePropertyChanged("HasDeviationMessageVersionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasDeviationMessageVersionIdSpecified {
            get {
                return this.hasDeviationMessageVersionIdFieldSpecified;
            }
            set {
                this.hasDeviationMessageVersionIdFieldSpecified = value;
                this.RaisePropertyChanged("HasDeviationMessageVersionIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ConsequenceLongCode {
            get {
                return this.consequenceLongCodeField;
            }
            set {
                this.consequenceLongCodeField = value;
                this.RaisePropertyChanged("ConsequenceLongCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetCallsforServiceJourneyMethodDatedArrival : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal idField;
        
        private bool idFieldSpecified;
        
        private decimal isOnDatedServiceJourneyIdField;
        
        private bool isOnDatedServiceJourneyIdFieldSpecified;
        
        private decimal isOnServiceJourneyIdField;
        
        private bool isOnServiceJourneyIdFieldSpecified;
        
        private decimal journeyPatternSequenceNumberField;
        
        private bool journeyPatternSequenceNumberFieldSpecified;
        
        private decimal isTimetabledAtJourneyPatternPointGidField;
        
        private bool isTimetabledAtJourneyPatternPointGidFieldSpecified;
        
        private decimal isTargetedAtJourneyPatternPointGidField;
        
        private bool isTargetedAtJourneyPatternPointGidFieldSpecified;
        
        private decimal wasObservedAtJourneyPatternPointGidField;
        
        private bool wasObservedAtJourneyPatternPointGidFieldSpecified;
        
        private System.DateTime timetabledLatestDateTimeField;
        
        private bool timetabledLatestDateTimeFieldSpecified;
        
        private System.DateTime targetDateTimeField;
        
        private bool targetDateTimeFieldSpecified;
        
        private System.DateTime estimatedDateTimeField;
        
        private bool estimatedDateTimeFieldSpecified;
        
        private System.DateTime observedDateTimeField;
        
        private bool observedDateTimeFieldSpecified;
        
        private short stateField;
        
        private bool stateFieldSpecified;
        
        private short typeField;
        
        private bool typeFieldSpecified;
        
        private int presentationTypeField;
        
        private bool presentationTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal IsOnDatedServiceJourneyId {
            get {
                return this.isOnDatedServiceJourneyIdField;
            }
            set {
                this.isOnDatedServiceJourneyIdField = value;
                this.RaisePropertyChanged("IsOnDatedServiceJourneyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsOnDatedServiceJourneyIdSpecified {
            get {
                return this.isOnDatedServiceJourneyIdFieldSpecified;
            }
            set {
                this.isOnDatedServiceJourneyIdFieldSpecified = value;
                this.RaisePropertyChanged("IsOnDatedServiceJourneyIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal IsOnServiceJourneyId {
            get {
                return this.isOnServiceJourneyIdField;
            }
            set {
                this.isOnServiceJourneyIdField = value;
                this.RaisePropertyChanged("IsOnServiceJourneyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsOnServiceJourneyIdSpecified {
            get {
                return this.isOnServiceJourneyIdFieldSpecified;
            }
            set {
                this.isOnServiceJourneyIdFieldSpecified = value;
                this.RaisePropertyChanged("IsOnServiceJourneyIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal JourneyPatternSequenceNumber {
            get {
                return this.journeyPatternSequenceNumberField;
            }
            set {
                this.journeyPatternSequenceNumberField = value;
                this.RaisePropertyChanged("JourneyPatternSequenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JourneyPatternSequenceNumberSpecified {
            get {
                return this.journeyPatternSequenceNumberFieldSpecified;
            }
            set {
                this.journeyPatternSequenceNumberFieldSpecified = value;
                this.RaisePropertyChanged("JourneyPatternSequenceNumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal IsTimetabledAtJourneyPatternPointGid {
            get {
                return this.isTimetabledAtJourneyPatternPointGidField;
            }
            set {
                this.isTimetabledAtJourneyPatternPointGidField = value;
                this.RaisePropertyChanged("IsTimetabledAtJourneyPatternPointGid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsTimetabledAtJourneyPatternPointGidSpecified {
            get {
                return this.isTimetabledAtJourneyPatternPointGidFieldSpecified;
            }
            set {
                this.isTimetabledAtJourneyPatternPointGidFieldSpecified = value;
                this.RaisePropertyChanged("IsTimetabledAtJourneyPatternPointGidSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal IsTargetedAtJourneyPatternPointGid {
            get {
                return this.isTargetedAtJourneyPatternPointGidField;
            }
            set {
                this.isTargetedAtJourneyPatternPointGidField = value;
                this.RaisePropertyChanged("IsTargetedAtJourneyPatternPointGid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsTargetedAtJourneyPatternPointGidSpecified {
            get {
                return this.isTargetedAtJourneyPatternPointGidFieldSpecified;
            }
            set {
                this.isTargetedAtJourneyPatternPointGidFieldSpecified = value;
                this.RaisePropertyChanged("IsTargetedAtJourneyPatternPointGidSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal WasObservedAtJourneyPatternPointGid {
            get {
                return this.wasObservedAtJourneyPatternPointGidField;
            }
            set {
                this.wasObservedAtJourneyPatternPointGidField = value;
                this.RaisePropertyChanged("WasObservedAtJourneyPatternPointGid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WasObservedAtJourneyPatternPointGidSpecified {
            get {
                return this.wasObservedAtJourneyPatternPointGidFieldSpecified;
            }
            set {
                this.wasObservedAtJourneyPatternPointGidFieldSpecified = value;
                this.RaisePropertyChanged("WasObservedAtJourneyPatternPointGidSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime TimetabledLatestDateTime {
            get {
                return this.timetabledLatestDateTimeField;
            }
            set {
                this.timetabledLatestDateTimeField = value;
                this.RaisePropertyChanged("TimetabledLatestDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimetabledLatestDateTimeSpecified {
            get {
                return this.timetabledLatestDateTimeFieldSpecified;
            }
            set {
                this.timetabledLatestDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("TimetabledLatestDateTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public System.DateTime TargetDateTime {
            get {
                return this.targetDateTimeField;
            }
            set {
                this.targetDateTimeField = value;
                this.RaisePropertyChanged("TargetDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TargetDateTimeSpecified {
            get {
                return this.targetDateTimeFieldSpecified;
            }
            set {
                this.targetDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("TargetDateTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public System.DateTime EstimatedDateTime {
            get {
                return this.estimatedDateTimeField;
            }
            set {
                this.estimatedDateTimeField = value;
                this.RaisePropertyChanged("EstimatedDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EstimatedDateTimeSpecified {
            get {
                return this.estimatedDateTimeFieldSpecified;
            }
            set {
                this.estimatedDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("EstimatedDateTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public System.DateTime ObservedDateTime {
            get {
                return this.observedDateTimeField;
            }
            set {
                this.observedDateTimeField = value;
                this.RaisePropertyChanged("ObservedDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ObservedDateTimeSpecified {
            get {
                return this.observedDateTimeFieldSpecified;
            }
            set {
                this.observedDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("ObservedDateTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public short State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StateSpecified {
            get {
                return this.stateFieldSpecified;
            }
            set {
                this.stateFieldSpecified = value;
                this.RaisePropertyChanged("StateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public short Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("TypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public int PresentationType {
            get {
                return this.presentationTypeField;
            }
            set {
                this.presentationTypeField = value;
                this.RaisePropertyChanged("PresentationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PresentationTypeSpecified {
            get {
                return this.presentationTypeFieldSpecified;
            }
            set {
                this.presentationTypeFieldSpecified = value;
                this.RaisePropertyChanged("PresentationTypeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetCallsforServiceJourneyMethodDatedDeparture : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal idField;
        
        private bool idFieldSpecified;
        
        private decimal isOnDatedServiceJourneyIdField;
        
        private bool isOnDatedServiceJourneyIdFieldSpecified;
        
        private decimal isOnServiceJourneyIdField;
        
        private bool isOnServiceJourneyIdFieldSpecified;
        
        private decimal journeyPatternSequenceNumberField;
        
        private bool journeyPatternSequenceNumberFieldSpecified;
        
        private decimal isTimetabledAtJourneyPatternPointGidField;
        
        private bool isTimetabledAtJourneyPatternPointGidFieldSpecified;
        
        private decimal isTargetedAtJourneyPatternPointGidField;
        
        private bool isTargetedAtJourneyPatternPointGidFieldSpecified;
        
        private decimal wasObservedAtJourneyPatternPointGidField;
        
        private bool wasObservedAtJourneyPatternPointGidFieldSpecified;
        
        private System.DateTime timetabledEarliestDateTimeField;
        
        private bool timetabledEarliestDateTimeFieldSpecified;
        
        private System.DateTime targetDateTimeField;
        
        private bool targetDateTimeFieldSpecified;
        
        private System.DateTime estimatedDateTimeField;
        
        private bool estimatedDateTimeFieldSpecified;
        
        private System.DateTime observedDateTimeField;
        
        private bool observedDateTimeFieldSpecified;
        
        private short stateField;
        
        private bool stateFieldSpecified;
        
        private short typeField;
        
        private bool typeFieldSpecified;
        
        private string productNameField;
        
        private string lineDesignationField;
        
        private string primaryDestinationNameField;
        
        private string primaryDestinationShortNameField;
        
        private string secondaryDestinationNameField;
        
        private string secondaryDestinationShortNameField;
        
        private string secondaryDestinationTypeField;
        
        private string symbolNameField;
        
        private int presentationTypeField;
        
        private bool presentationTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal IsOnDatedServiceJourneyId {
            get {
                return this.isOnDatedServiceJourneyIdField;
            }
            set {
                this.isOnDatedServiceJourneyIdField = value;
                this.RaisePropertyChanged("IsOnDatedServiceJourneyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsOnDatedServiceJourneyIdSpecified {
            get {
                return this.isOnDatedServiceJourneyIdFieldSpecified;
            }
            set {
                this.isOnDatedServiceJourneyIdFieldSpecified = value;
                this.RaisePropertyChanged("IsOnDatedServiceJourneyIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal IsOnServiceJourneyId {
            get {
                return this.isOnServiceJourneyIdField;
            }
            set {
                this.isOnServiceJourneyIdField = value;
                this.RaisePropertyChanged("IsOnServiceJourneyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsOnServiceJourneyIdSpecified {
            get {
                return this.isOnServiceJourneyIdFieldSpecified;
            }
            set {
                this.isOnServiceJourneyIdFieldSpecified = value;
                this.RaisePropertyChanged("IsOnServiceJourneyIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal JourneyPatternSequenceNumber {
            get {
                return this.journeyPatternSequenceNumberField;
            }
            set {
                this.journeyPatternSequenceNumberField = value;
                this.RaisePropertyChanged("JourneyPatternSequenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JourneyPatternSequenceNumberSpecified {
            get {
                return this.journeyPatternSequenceNumberFieldSpecified;
            }
            set {
                this.journeyPatternSequenceNumberFieldSpecified = value;
                this.RaisePropertyChanged("JourneyPatternSequenceNumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal IsTimetabledAtJourneyPatternPointGid {
            get {
                return this.isTimetabledAtJourneyPatternPointGidField;
            }
            set {
                this.isTimetabledAtJourneyPatternPointGidField = value;
                this.RaisePropertyChanged("IsTimetabledAtJourneyPatternPointGid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsTimetabledAtJourneyPatternPointGidSpecified {
            get {
                return this.isTimetabledAtJourneyPatternPointGidFieldSpecified;
            }
            set {
                this.isTimetabledAtJourneyPatternPointGidFieldSpecified = value;
                this.RaisePropertyChanged("IsTimetabledAtJourneyPatternPointGidSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal IsTargetedAtJourneyPatternPointGid {
            get {
                return this.isTargetedAtJourneyPatternPointGidField;
            }
            set {
                this.isTargetedAtJourneyPatternPointGidField = value;
                this.RaisePropertyChanged("IsTargetedAtJourneyPatternPointGid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsTargetedAtJourneyPatternPointGidSpecified {
            get {
                return this.isTargetedAtJourneyPatternPointGidFieldSpecified;
            }
            set {
                this.isTargetedAtJourneyPatternPointGidFieldSpecified = value;
                this.RaisePropertyChanged("IsTargetedAtJourneyPatternPointGidSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal WasObservedAtJourneyPatternPointGid {
            get {
                return this.wasObservedAtJourneyPatternPointGidField;
            }
            set {
                this.wasObservedAtJourneyPatternPointGidField = value;
                this.RaisePropertyChanged("WasObservedAtJourneyPatternPointGid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WasObservedAtJourneyPatternPointGidSpecified {
            get {
                return this.wasObservedAtJourneyPatternPointGidFieldSpecified;
            }
            set {
                this.wasObservedAtJourneyPatternPointGidFieldSpecified = value;
                this.RaisePropertyChanged("WasObservedAtJourneyPatternPointGidSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime TimetabledEarliestDateTime {
            get {
                return this.timetabledEarliestDateTimeField;
            }
            set {
                this.timetabledEarliestDateTimeField = value;
                this.RaisePropertyChanged("TimetabledEarliestDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimetabledEarliestDateTimeSpecified {
            get {
                return this.timetabledEarliestDateTimeFieldSpecified;
            }
            set {
                this.timetabledEarliestDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("TimetabledEarliestDateTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public System.DateTime TargetDateTime {
            get {
                return this.targetDateTimeField;
            }
            set {
                this.targetDateTimeField = value;
                this.RaisePropertyChanged("TargetDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TargetDateTimeSpecified {
            get {
                return this.targetDateTimeFieldSpecified;
            }
            set {
                this.targetDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("TargetDateTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public System.DateTime EstimatedDateTime {
            get {
                return this.estimatedDateTimeField;
            }
            set {
                this.estimatedDateTimeField = value;
                this.RaisePropertyChanged("EstimatedDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EstimatedDateTimeSpecified {
            get {
                return this.estimatedDateTimeFieldSpecified;
            }
            set {
                this.estimatedDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("EstimatedDateTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public System.DateTime ObservedDateTime {
            get {
                return this.observedDateTimeField;
            }
            set {
                this.observedDateTimeField = value;
                this.RaisePropertyChanged("ObservedDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ObservedDateTimeSpecified {
            get {
                return this.observedDateTimeFieldSpecified;
            }
            set {
                this.observedDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("ObservedDateTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public short State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StateSpecified {
            get {
                return this.stateFieldSpecified;
            }
            set {
                this.stateFieldSpecified = value;
                this.RaisePropertyChanged("StateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public short Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("TypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("ProductName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string LineDesignation {
            get {
                return this.lineDesignationField;
            }
            set {
                this.lineDesignationField = value;
                this.RaisePropertyChanged("LineDesignation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string PrimaryDestinationName {
            get {
                return this.primaryDestinationNameField;
            }
            set {
                this.primaryDestinationNameField = value;
                this.RaisePropertyChanged("PrimaryDestinationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string PrimaryDestinationShortName {
            get {
                return this.primaryDestinationShortNameField;
            }
            set {
                this.primaryDestinationShortNameField = value;
                this.RaisePropertyChanged("PrimaryDestinationShortName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string SecondaryDestinationName {
            get {
                return this.secondaryDestinationNameField;
            }
            set {
                this.secondaryDestinationNameField = value;
                this.RaisePropertyChanged("SecondaryDestinationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string SecondaryDestinationShortName {
            get {
                return this.secondaryDestinationShortNameField;
            }
            set {
                this.secondaryDestinationShortNameField = value;
                this.RaisePropertyChanged("SecondaryDestinationShortName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string SecondaryDestinationType {
            get {
                return this.secondaryDestinationTypeField;
            }
            set {
                this.secondaryDestinationTypeField = value;
                this.RaisePropertyChanged("SecondaryDestinationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string SymbolName {
            get {
                return this.symbolNameField;
            }
            set {
                this.symbolNameField = value;
                this.RaisePropertyChanged("SymbolName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public int PresentationType {
            get {
                return this.presentationTypeField;
            }
            set {
                this.presentationTypeField = value;
                this.RaisePropertyChanged("PresentationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PresentationTypeSpecified {
            get {
                return this.presentationTypeFieldSpecified;
            }
            set {
                this.presentationTypeFieldSpecified = value;
                this.RaisePropertyChanged("PresentationTypeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetCallsforServiceJourneyMethodDatedServiceJourney : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal idField;
        
        private bool idFieldSpecified;
        
        private decimal datedVehicleJourneyIdField;
        
        private bool datedVehicleJourneyIdFieldSpecified;
        
        private decimal isDatedVehicleJourneyIdField;
        
        private bool isDatedVehicleJourneyIdFieldSpecified;
        
        private System.DateTime operatingDayDateField;
        
        private bool operatingDayDateFieldSpecified;
        
        private decimal gidField;
        
        private bool gidFieldSpecified;
        
        private decimal isWorkedOnDirectionOfLineGidField;
        
        private bool isWorkedOnDirectionOfLineGidFieldSpecified;
        
        private string transportModeCodeField;
        
        private string lineDesignationField;
        
        private string transportAuthorityCodeField;
        
        private string transportAuthorityNameField;
        
        private string contractorCodeField;
        
        private string contractorNameField;
        
        private bool expectedToBeMonitoredField;
        
        private bool expectedToBeMonitoredFieldSpecified;
        
        private decimal isAssignedToVehicleGidField;
        
        private bool isAssignedToVehicleGidFieldSpecified;
        
        private short stateField;
        
        private bool stateFieldSpecified;
        
        private short predictionStateField;
        
        private bool predictionStateFieldSpecified;
        
        private string originNameField;
        
        private string originShortNameField;
        
        private string productCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal DatedVehicleJourneyId {
            get {
                return this.datedVehicleJourneyIdField;
            }
            set {
                this.datedVehicleJourneyIdField = value;
                this.RaisePropertyChanged("DatedVehicleJourneyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatedVehicleJourneyIdSpecified {
            get {
                return this.datedVehicleJourneyIdFieldSpecified;
            }
            set {
                this.datedVehicleJourneyIdFieldSpecified = value;
                this.RaisePropertyChanged("DatedVehicleJourneyIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal IsDatedVehicleJourneyId {
            get {
                return this.isDatedVehicleJourneyIdField;
            }
            set {
                this.isDatedVehicleJourneyIdField = value;
                this.RaisePropertyChanged("IsDatedVehicleJourneyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsDatedVehicleJourneyIdSpecified {
            get {
                return this.isDatedVehicleJourneyIdFieldSpecified;
            }
            set {
                this.isDatedVehicleJourneyIdFieldSpecified = value;
                this.RaisePropertyChanged("IsDatedVehicleJourneyIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime OperatingDayDate {
            get {
                return this.operatingDayDateField;
            }
            set {
                this.operatingDayDateField = value;
                this.RaisePropertyChanged("OperatingDayDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OperatingDayDateSpecified {
            get {
                return this.operatingDayDateFieldSpecified;
            }
            set {
                this.operatingDayDateFieldSpecified = value;
                this.RaisePropertyChanged("OperatingDayDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal Gid {
            get {
                return this.gidField;
            }
            set {
                this.gidField = value;
                this.RaisePropertyChanged("Gid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GidSpecified {
            get {
                return this.gidFieldSpecified;
            }
            set {
                this.gidFieldSpecified = value;
                this.RaisePropertyChanged("GidSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal IsWorkedOnDirectionOfLineGid {
            get {
                return this.isWorkedOnDirectionOfLineGidField;
            }
            set {
                this.isWorkedOnDirectionOfLineGidField = value;
                this.RaisePropertyChanged("IsWorkedOnDirectionOfLineGid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsWorkedOnDirectionOfLineGidSpecified {
            get {
                return this.isWorkedOnDirectionOfLineGidFieldSpecified;
            }
            set {
                this.isWorkedOnDirectionOfLineGidFieldSpecified = value;
                this.RaisePropertyChanged("IsWorkedOnDirectionOfLineGidSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string TransportModeCode {
            get {
                return this.transportModeCodeField;
            }
            set {
                this.transportModeCodeField = value;
                this.RaisePropertyChanged("TransportModeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string LineDesignation {
            get {
                return this.lineDesignationField;
            }
            set {
                this.lineDesignationField = value;
                this.RaisePropertyChanged("LineDesignation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string TransportAuthorityCode {
            get {
                return this.transportAuthorityCodeField;
            }
            set {
                this.transportAuthorityCodeField = value;
                this.RaisePropertyChanged("TransportAuthorityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string TransportAuthorityName {
            get {
                return this.transportAuthorityNameField;
            }
            set {
                this.transportAuthorityNameField = value;
                this.RaisePropertyChanged("TransportAuthorityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ContractorCode {
            get {
                return this.contractorCodeField;
            }
            set {
                this.contractorCodeField = value;
                this.RaisePropertyChanged("ContractorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ContractorName {
            get {
                return this.contractorNameField;
            }
            set {
                this.contractorNameField = value;
                this.RaisePropertyChanged("ContractorName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public bool ExpectedToBeMonitored {
            get {
                return this.expectedToBeMonitoredField;
            }
            set {
                this.expectedToBeMonitoredField = value;
                this.RaisePropertyChanged("ExpectedToBeMonitored");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpectedToBeMonitoredSpecified {
            get {
                return this.expectedToBeMonitoredFieldSpecified;
            }
            set {
                this.expectedToBeMonitoredFieldSpecified = value;
                this.RaisePropertyChanged("ExpectedToBeMonitoredSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public decimal IsAssignedToVehicleGid {
            get {
                return this.isAssignedToVehicleGidField;
            }
            set {
                this.isAssignedToVehicleGidField = value;
                this.RaisePropertyChanged("IsAssignedToVehicleGid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsAssignedToVehicleGidSpecified {
            get {
                return this.isAssignedToVehicleGidFieldSpecified;
            }
            set {
                this.isAssignedToVehicleGidFieldSpecified = value;
                this.RaisePropertyChanged("IsAssignedToVehicleGidSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public short State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StateSpecified {
            get {
                return this.stateFieldSpecified;
            }
            set {
                this.stateFieldSpecified = value;
                this.RaisePropertyChanged("StateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public short PredictionState {
            get {
                return this.predictionStateField;
            }
            set {
                this.predictionStateField = value;
                this.RaisePropertyChanged("PredictionState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PredictionStateSpecified {
            get {
                return this.predictionStateFieldSpecified;
            }
            set {
                this.predictionStateFieldSpecified = value;
                this.RaisePropertyChanged("PredictionStateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string OriginName {
            get {
                return this.originNameField;
            }
            set {
                this.originNameField = value;
                this.RaisePropertyChanged("OriginName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string OriginShortName {
            get {
                return this.originShortNameField;
            }
            set {
                this.originShortNameField = value;
                this.RaisePropertyChanged("OriginShortName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
                this.RaisePropertyChanged("ProductCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetCallsforServiceJourneyMethodDepartureDeviation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal idField;
        
        private bool idFieldSpecified;
        
        private decimal isOnDepartureIdField;
        
        private bool isOnDepartureIdFieldSpecified;
        
        private bool affectsLaterArrivalsYesNoField;
        
        private bool affectsLaterArrivalsYesNoFieldSpecified;
        
        private decimal hasDeviationMessageVersionIdField;
        
        private bool hasDeviationMessageVersionIdFieldSpecified;
        
        private string consequenceLongCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal IsOnDepartureId {
            get {
                return this.isOnDepartureIdField;
            }
            set {
                this.isOnDepartureIdField = value;
                this.RaisePropertyChanged("IsOnDepartureId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsOnDepartureIdSpecified {
            get {
                return this.isOnDepartureIdFieldSpecified;
            }
            set {
                this.isOnDepartureIdFieldSpecified = value;
                this.RaisePropertyChanged("IsOnDepartureIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool AffectsLaterArrivalsYesNo {
            get {
                return this.affectsLaterArrivalsYesNoField;
            }
            set {
                this.affectsLaterArrivalsYesNoField = value;
                this.RaisePropertyChanged("AffectsLaterArrivalsYesNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AffectsLaterArrivalsYesNoSpecified {
            get {
                return this.affectsLaterArrivalsYesNoFieldSpecified;
            }
            set {
                this.affectsLaterArrivalsYesNoFieldSpecified = value;
                this.RaisePropertyChanged("AffectsLaterArrivalsYesNoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal HasDeviationMessageVersionId {
            get {
                return this.hasDeviationMessageVersionIdField;
            }
            set {
                this.hasDeviationMessageVersionIdField = value;
                this.RaisePropertyChanged("HasDeviationMessageVersionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasDeviationMessageVersionIdSpecified {
            get {
                return this.hasDeviationMessageVersionIdFieldSpecified;
            }
            set {
                this.hasDeviationMessageVersionIdFieldSpecified = value;
                this.RaisePropertyChanged("HasDeviationMessageVersionIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ConsequenceLongCode {
            get {
                return this.consequenceLongCodeField;
            }
            set {
                this.consequenceLongCodeField = value;
                this.RaisePropertyChanged("ConsequenceLongCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetCallsforServiceJourneyMethodDeviationMessageVariant : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal idField;
        
        private bool idFieldSpecified;
        
        private decimal isPartOfDeviationMessageIdField;
        
        private bool isPartOfDeviationMessageIdFieldSpecified;
        
        private string contentField;
        
        private string contentTypeLongCodeField;
        
        private string usageTypeLongCodeField;
        
        private string languageCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal IsPartOfDeviationMessageId {
            get {
                return this.isPartOfDeviationMessageIdField;
            }
            set {
                this.isPartOfDeviationMessageIdField = value;
                this.RaisePropertyChanged("IsPartOfDeviationMessageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsPartOfDeviationMessageIdSpecified {
            get {
                return this.isPartOfDeviationMessageIdFieldSpecified;
            }
            set {
                this.isPartOfDeviationMessageIdFieldSpecified = value;
                this.RaisePropertyChanged("IsPartOfDeviationMessageIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("Content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ContentTypeLongCode {
            get {
                return this.contentTypeLongCodeField;
            }
            set {
                this.contentTypeLongCodeField = value;
                this.RaisePropertyChanged("ContentTypeLongCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string UsageTypeLongCode {
            get {
                return this.usageTypeLongCodeField;
            }
            set {
                this.usageTypeLongCodeField = value;
                this.RaisePropertyChanged("UsageTypeLongCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
                this.RaisePropertyChanged("LanguageCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetCallsforServiceJourneyMethodDeviationMessageVersion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal idField;
        
        private bool idFieldSpecified;
        
        private string publicNoteField;
        
        private string internalNoteField;
        
        private short priorityImportanceLevelField;
        
        private bool priorityImportanceLevelFieldSpecified;
        
        private short priorityInfluenceLevelField;
        
        private bool priorityInfluenceLevelFieldSpecified;
        
        private short priorityUrgencyLevelField;
        
        private bool priorityUrgencyLevelFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PublicNote {
            get {
                return this.publicNoteField;
            }
            set {
                this.publicNoteField = value;
                this.RaisePropertyChanged("PublicNote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string InternalNote {
            get {
                return this.internalNoteField;
            }
            set {
                this.internalNoteField = value;
                this.RaisePropertyChanged("InternalNote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public short PriorityImportanceLevel {
            get {
                return this.priorityImportanceLevelField;
            }
            set {
                this.priorityImportanceLevelField = value;
                this.RaisePropertyChanged("PriorityImportanceLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriorityImportanceLevelSpecified {
            get {
                return this.priorityImportanceLevelFieldSpecified;
            }
            set {
                this.priorityImportanceLevelFieldSpecified = value;
                this.RaisePropertyChanged("PriorityImportanceLevelSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public short PriorityInfluenceLevel {
            get {
                return this.priorityInfluenceLevelField;
            }
            set {
                this.priorityInfluenceLevelField = value;
                this.RaisePropertyChanged("PriorityInfluenceLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriorityInfluenceLevelSpecified {
            get {
                return this.priorityInfluenceLevelFieldSpecified;
            }
            set {
                this.priorityInfluenceLevelFieldSpecified = value;
                this.RaisePropertyChanged("PriorityInfluenceLevelSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public short PriorityUrgencyLevel {
            get {
                return this.priorityUrgencyLevelField;
            }
            set {
                this.priorityUrgencyLevelField = value;
                this.RaisePropertyChanged("PriorityUrgencyLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriorityUrgencyLevelSpecified {
            get {
                return this.priorityUrgencyLevelFieldSpecified;
            }
            set {
                this.priorityUrgencyLevelFieldSpecified = value;
                this.RaisePropertyChanged("PriorityUrgencyLevelSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetCallsforServiceJourneyMethodServiceJourneyDeviation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal idField;
        
        private bool idFieldSpecified;
        
        private decimal isOnDatedVehicleJourneyIdField;
        
        private bool isOnDatedVehicleJourneyIdFieldSpecified;
        
        private decimal hasDeviationMessageVersionIdField;
        
        private bool hasDeviationMessageVersionIdFieldSpecified;
        
        private string consequenceLongCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal IsOnDatedVehicleJourneyId {
            get {
                return this.isOnDatedVehicleJourneyIdField;
            }
            set {
                this.isOnDatedVehicleJourneyIdField = value;
                this.RaisePropertyChanged("IsOnDatedVehicleJourneyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsOnDatedVehicleJourneyIdSpecified {
            get {
                return this.isOnDatedVehicleJourneyIdFieldSpecified;
            }
            set {
                this.isOnDatedVehicleJourneyIdFieldSpecified = value;
                this.RaisePropertyChanged("IsOnDatedVehicleJourneyIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal HasDeviationMessageVersionId {
            get {
                return this.hasDeviationMessageVersionIdField;
            }
            set {
                this.hasDeviationMessageVersionIdField = value;
                this.RaisePropertyChanged("HasDeviationMessageVersionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasDeviationMessageVersionIdSpecified {
            get {
                return this.hasDeviationMessageVersionIdFieldSpecified;
            }
            set {
                this.hasDeviationMessageVersionIdFieldSpecified = value;
                this.RaisePropertyChanged("HasDeviationMessageVersionIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ConsequenceLongCode {
            get {
                return this.consequenceLongCodeField;
            }
            set {
                this.consequenceLongCodeField = value;
                this.RaisePropertyChanged("ConsequenceLongCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetCallsforServiceJourneyMethodTargetAudience : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal isForDeviationMessageVersionIdField;
        
        private bool isForDeviationMessageVersionIdFieldSpecified;
        
        private string typeCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal IsForDeviationMessageVersionId {
            get {
                return this.isForDeviationMessageVersionIdField;
            }
            set {
                this.isForDeviationMessageVersionIdField = value;
                this.RaisePropertyChanged("IsForDeviationMessageVersionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsForDeviationMessageVersionIdSpecified {
            get {
                return this.isForDeviationMessageVersionIdFieldSpecified;
            }
            set {
                this.isForDeviationMessageVersionIdFieldSpecified = value;
                this.RaisePropertyChanged("IsForDeviationMessageVersionIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TypeCode {
            get {
                return this.typeCodeField;
            }
            set {
                this.typeCodeField = value;
                this.RaisePropertyChanged("TypeCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCallsForServiceJourneyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.skanestrafiken.com/DK/INTSTDK001/GetCallsForServiceJourney/20141020", Order=0)]
        public CGIXrmExtConnectorService.SvcCallsForServiceJourney.GetCallsforServiceJourney GetCallsforServiceJourney;
        
        public GetCallsForServiceJourneyRequest() {
        }
        
        public GetCallsForServiceJourneyRequest(CGIXrmExtConnectorService.SvcCallsForServiceJourney.GetCallsforServiceJourney GetCallsforServiceJourney) {
            this.GetCallsforServiceJourney = GetCallsforServiceJourney;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCallsForServiceJourneyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wwww.skanetrafiken.com/DK/INTSTDK001/GetCallsForServiceJourneyResponse/201" +
            "41020", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrivalDeviation", typeof(GetCallsforServiceJourneyMethodArrivalDeviation), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DatedArrival", typeof(GetCallsforServiceJourneyMethodDatedArrival), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DatedDeparture", typeof(GetCallsforServiceJourneyMethodDatedDeparture), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DatedServiceJourney", typeof(GetCallsforServiceJourneyMethodDatedServiceJourney), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DepartureDeviation", typeof(GetCallsforServiceJourneyMethodDepartureDeviation), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DeviationMessageVariant", typeof(GetCallsforServiceJourneyMethodDeviationMessageVariant), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DeviationMessageVersion", typeof(GetCallsforServiceJourneyMethodDeviationMessageVersion), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ServiceJourneyDeviation", typeof(GetCallsforServiceJourneyMethodServiceJourneyDeviation), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TargetAudience", typeof(GetCallsforServiceJourneyMethodTargetAudience), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public object[] GetCallsforServiceJourneyMethod;
        
        public GetCallsForServiceJourneyResponse() {
        }
        
        public GetCallsForServiceJourneyResponse(object[] GetCallsforServiceJourneyMethod) {
            this.GetCallsforServiceJourneyMethod = GetCallsforServiceJourneyMethod;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CallsForServiceJourneyChannel : CGIXrmExtConnectorService.SvcCallsForServiceJourney.CallsForServiceJourney, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CallsForServiceJourneyClient : System.ServiceModel.ClientBase<CGIXrmExtConnectorService.SvcCallsForServiceJourney.CallsForServiceJourney>, CGIXrmExtConnectorService.SvcCallsForServiceJourney.CallsForServiceJourney {
        
        public CallsForServiceJourneyClient() {
        }
        
        public CallsForServiceJourneyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CallsForServiceJourneyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CallsForServiceJourneyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CallsForServiceJourneyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CGIXrmExtConnectorService.SvcCallsForServiceJourney.GetCallsForServiceJourneyResponse CGIXrmExtConnectorService.SvcCallsForServiceJourney.CallsForServiceJourney.GetCallsForServiceJourney(CGIXrmExtConnectorService.SvcCallsForServiceJourney.GetCallsForServiceJourneyRequest request) {
            return base.Channel.GetCallsForServiceJourney(request);
        }
        
        public object[] GetCallsForServiceJourney(CGIXrmExtConnectorService.SvcCallsForServiceJourney.GetCallsforServiceJourney GetCallsforServiceJourney1) {
            CGIXrmExtConnectorService.SvcCallsForServiceJourney.GetCallsForServiceJourneyRequest inValue = new CGIXrmExtConnectorService.SvcCallsForServiceJourney.GetCallsForServiceJourneyRequest();
            inValue.GetCallsforServiceJourney = GetCallsforServiceJourney1;
            CGIXrmExtConnectorService.SvcCallsForServiceJourney.GetCallsForServiceJourneyResponse retVal = ((CGIXrmExtConnectorService.SvcCallsForServiceJourney.CallsForServiceJourney)(this)).GetCallsForServiceJourney(inValue);
            return retVal.GetCallsforServiceJourneyMethod;
        }
    }
}
