CREATE TABLE [dbo].[Counter](
	[CounterName] [nvarchar](50) NOT NULL,
	[LastValue] [int] NOT NULL,
 CONSTRAINT [PK_Counter] PRIMARY KEY CLUSTERED 
(
	[CounterName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Counter] ADD  CONSTRAINT [DF_Table_1_NextValue]  DEFAULT ((0)) FOR [LastValue]
GO