


--
-- base view for QueueItem
--
create view dbo.[QueueItem]
 (
    -- logical attributes
    [ModifiedOnBehalfByName],
    [ModifiedByYomiName],
    [OwningUser],
    [CreatedByYomiName],
    [OwnerId],
    [ModifiedByName],
    [CreatedOnBehalfByName],
    [QueueIdName],
    [CreatedOnBehalfByYomiName],
    [ModifiedOnBehalfByYomiName],
    [OwnerIdType],
    [CreatedByName],
    [TransactionCurrencyIdName],
    [OrganizationIdName],
    [OwningBusinessUnit],

    ObjectIdName,
    ObjectIdTypeCode,
    -- physical attributes
    [QueueItemId],
    [QueueId],
    [ObjectId],
    [ObjectTypeCode],
    [Title],
    [EnteredOn],
    [Priority],
    [State],
    [Status],
    [CreatedOn],
    [CreatedBy],
    [ModifiedBy],
    [ModifiedOn],
    [ToRecipients],
    [Sender],
    [OrganizationId],
    [VersionNumber],
    [TimeZoneRuleVersionNumber],
    [UTCConversionTimeZoneCode],
    [OverriddenCreatedOn],
    [WorkerIdModifiedOn],
    [WorkerId],
    [StatusCode],
    [StateCode],
    [WorkerIdName],
    [WorkerIdYomiName],
    [CreatedOnBehalfBy],
    [ModifiedOnBehalfBy],
    [TransactionCurrencyId],
    [ExchangeRate],
    [ImportSequenceNumber],
    [WorkerIdType],
    [cgi_incidentstagecode],
    [cgi_priority],
    [cgi_customer],
    [cgi_case_type],
    [cgi_case_remittance],
    [cgi_action_date],
    [cgi_resolve_by],
    [cgi_customer_number],
    [cgi_customer_email],
    [cgi_soc_sec_number],
    [cgi_customer_telephonenumber],
    [cgi_customer_telephonenumber_work],
    [cgi_customer_telephonenumber_mobile],
    [cgi_arrival_date],
    [cgi_ticketnumber],
    [cgi_caseorigincode],
    [cgi_casdet_row1_cat3],
    [cgi_refund_type],
    [cgi_refund_status],
    [cgi_travelinformationline],
    [cgi_refund_approvaltype],
    [cgi_refund_typename],
    [cgi_reimbursement_name]
) with view_metadata as
select
    -- logical attributes
    [lk_queueitembase_modifiedonbehalfby].[FullName],
    [lk_queueitembase_modifiedby].[YomiFullName],
    case when [queue_entries].OwnerIdType = 8
    then [queue_entries].OwnerId
    else null
    end,
    [lk_queueitembase_createdby].[YomiFullName],
    [queue_entries].[OwnerId],
    [lk_queueitembase_modifiedby].[FullName],
    [lk_queueitembase_createdonbehalfby].[FullName],
    [queue_entries].[Name],
    [lk_queueitembase_createdonbehalfby].[YomiFullName],
    [lk_queueitembase_modifiedonbehalfby].[YomiFullName],
    [queue_entries].[OwnerIdType],
    [lk_queueitembase_createdby].[FullName],
    [TransactionCurrency_QueueItem].[CurrencyName],
    [organization_queueitems].[Name],
    [queue_entries].[OwningBusinessUnit],

-- logical attribute 
			QueueItemBase.Title,
QueueItemBase.ObjectTypeCode,    -- physical attribute
    [QueueItemBase].[QueueItemId],
    [QueueItemBase].[QueueId],
    [QueueItemBase].[ObjectId],
    [QueueItemBase].[ObjectTypeCode],
    [QueueItemBase].[Title],
    [QueueItemBase].[EnteredOn],
    [QueueItemBase].[Priority],
    [QueueItemBase].[State],
    [QueueItemBase].[Status],
    [QueueItemBase].[CreatedOn],
    [QueueItemBase].[CreatedBy],
    [QueueItemBase].[ModifiedBy],
    [QueueItemBase].[ModifiedOn],
    [QueueItemBase].[ToRecipients],
    [QueueItemBase].[Sender],
    [QueueItemBase].[OrganizationId],
    [QueueItemBase].[VersionNumber],
    [QueueItemBase].[TimeZoneRuleVersionNumber],
    [QueueItemBase].[UTCConversionTimeZoneCode],
    [QueueItemBase].[OverriddenCreatedOn],
    [QueueItemBase].[WorkerIdModifiedOn],
    [QueueItemBase].[WorkerId],
    [QueueItemBase].[StatusCode],
    [QueueItemBase].[StateCode],
    [QueueItemBase].[WorkerIdName],
    [QueueItemBase].[WorkerIdYomiName],
    [QueueItemBase].[CreatedOnBehalfBy],
    [QueueItemBase].[ModifiedOnBehalfBy],
    [QueueItemBase].[TransactionCurrencyId],
    [QueueItemBase].[ExchangeRate],
    [QueueItemBase].[ImportSequenceNumber],
    [QueueItemBase].[WorkerIdType],
    [QueueItemBase].[cgi_incidentstagecode],
    [QueueItemBase].[cgi_priority],
    [QueueItemBase].[cgi_customer],
    [QueueItemBase].[cgi_case_type],
    [QueueItemBase].[cgi_case_remittance],
    [QueueItemBase].[cgi_action_date],
    [QueueItemBase].[cgi_resolve_by],
    [QueueItemBase].[cgi_customer_number],
    [QueueItemBase].[cgi_customer_email],
    [QueueItemBase].[cgi_soc_sec_number],
    [QueueItemBase].[cgi_customer_telephonenumber],
    [QueueItemBase].[cgi_customer_telephonenumber_work],
    [QueueItemBase].[cgi_customer_telephonenumber_mobile],
    [QueueItemBase].[cgi_arrival_date],
    [QueueItemBase].[cgi_ticketnumber],
    [QueueItemBase].[cgi_caseorigincode],
    [QueueItemBase].[cgi_casdet_row1_cat3],
    [QueueItemBase].[cgi_refund_type],
    [QueueItemBase].[cgi_refund_status],
    [QueueItemBase].[cgi_travelinformationline],
    [QueueItemBase].[cgi_refund_approvaltype],
    [QueueItemBase].[cgi_refund_typename],
    [QueueItemBase].[cgi_reimbursement_name]
from [QueueItemBase] 
    left join [SystemUserBase] [lk_queueitembase_createdby] with(nolock) on ([QueueItemBase].[CreatedBy] = [lk_queueitembase_createdby].[SystemUserId])
    left join [SystemUserBase] [lk_queueitembase_createdonbehalfby] with(nolock) on ([QueueItemBase].[CreatedOnBehalfBy] = [lk_queueitembase_createdonbehalfby].[SystemUserId])
    left join [SystemUserBase] [lk_queueitembase_modifiedby] with(nolock) on ([QueueItemBase].[ModifiedBy] = [lk_queueitembase_modifiedby].[SystemUserId])
    left join [SystemUserBase] [lk_queueitembase_modifiedonbehalfby] with(nolock) on ([QueueItemBase].[ModifiedOnBehalfBy] = [lk_queueitembase_modifiedonbehalfby].[SystemUserId])
    left join [OrganizationBase] [organization_queueitems] with(nolock) on ([QueueItemBase].[OrganizationId] = [organization_queueitems].[OrganizationId])
    left join [QueueBase] [queue_entries] on ([QueueItemBase].[QueueId] = [queue_entries].[QueueId])
    left join [TransactionCurrencyBase] [TransactionCurrency_QueueItem] on ([QueueItemBase].[TransactionCurrencyId] = [TransactionCurrency_QueueItem].[TransactionCurrencyId])
