//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace CRM.GetBIFFTransactions.TravelCardService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCardDetailsResponse", Namespace="http://schemas.datacontract.org/2004/07/CGIXrmTravelCard")]
    public partial class GetCardDetailsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CardDetailsField;
        
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardDetails {
            get {
                return this.CardDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.CardDetailsField, value) != true)) {
                    this.CardDetailsField = value;
                    this.RaisePropertyChanged("CardDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCRMCardDetailsResponse", Namespace="http://schemas.datacontract.org/2004/07/CGIXrmTravelCard")]
    public partial class GetCRMCardDetailsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CRM.GetBIFFTransactions.TravelCardService.Card CardField;
        
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CRM.GetBIFFTransactions.TravelCardService.Card Card {
            get {
                return this.CardField;
            }
            set {
                if ((object.ReferenceEquals(this.CardField, value) != true)) {
                    this.CardField = value;
                    this.RaisePropertyChanged("Card");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Card", Namespace="http://schemas.datacontract.org/2004/07/CGIXrmTravelCard")]
    public partial class Card : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<System.Guid> AccountIdField;
        
        private string AccountIdNameField;
        
        private string AccountNumberField;
        
        private string AutoloadconnectiondateField;
        
        private string AutoloaddisconnectiondateField;
        
        private int AutoloadstatusField;
        
        private string AutoloadstatusnameField;
        
        private System.Nullable<int> BlockedField;
        
        private System.Nullable<System.Guid> CardTypeIdField;
        
        private string CardTypeIdNameField;
        
        private System.Nullable<System.Guid> ContactIdField;
        
        private string ContactIdNameField;
        
        private string ContactnumberField;
        
        private string CreditcardmaskField;
        
        private string FailedattemptstochargemoneyField;
        
        private string NumberOfZonesField;
        
        private string PeriodeicCardTypeField;
        
        private int StateCodeField;
        
        private System.Guid TravelCardIDField;
        
        private string TravelCardNameField;
        
        private string ValidFromField;
        
        private string ValidToField;
        
        private string Value_card_typeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountIdName {
            get {
                return this.AccountIdNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountIdNameField, value) != true)) {
                    this.AccountIdNameField = value;
                    this.RaisePropertyChanged("AccountIdName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autoloadconnectiondate {
            get {
                return this.AutoloadconnectiondateField;
            }
            set {
                if ((object.ReferenceEquals(this.AutoloadconnectiondateField, value) != true)) {
                    this.AutoloadconnectiondateField = value;
                    this.RaisePropertyChanged("Autoloadconnectiondate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autoloaddisconnectiondate {
            get {
                return this.AutoloaddisconnectiondateField;
            }
            set {
                if ((object.ReferenceEquals(this.AutoloaddisconnectiondateField, value) != true)) {
                    this.AutoloaddisconnectiondateField = value;
                    this.RaisePropertyChanged("Autoloaddisconnectiondate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Autoloadstatus {
            get {
                return this.AutoloadstatusField;
            }
            set {
                if ((this.AutoloadstatusField.Equals(value) != true)) {
                    this.AutoloadstatusField = value;
                    this.RaisePropertyChanged("Autoloadstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autoloadstatusname {
            get {
                return this.AutoloadstatusnameField;
            }
            set {
                if ((object.ReferenceEquals(this.AutoloadstatusnameField, value) != true)) {
                    this.AutoloadstatusnameField = value;
                    this.RaisePropertyChanged("Autoloadstatusname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Blocked {
            get {
                return this.BlockedField;
            }
            set {
                if ((this.BlockedField.Equals(value) != true)) {
                    this.BlockedField = value;
                    this.RaisePropertyChanged("Blocked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> CardTypeId {
            get {
                return this.CardTypeIdField;
            }
            set {
                if ((this.CardTypeIdField.Equals(value) != true)) {
                    this.CardTypeIdField = value;
                    this.RaisePropertyChanged("CardTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardTypeIdName {
            get {
                return this.CardTypeIdNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CardTypeIdNameField, value) != true)) {
                    this.CardTypeIdNameField = value;
                    this.RaisePropertyChanged("CardTypeIdName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ContactId {
            get {
                return this.ContactIdField;
            }
            set {
                if ((this.ContactIdField.Equals(value) != true)) {
                    this.ContactIdField = value;
                    this.RaisePropertyChanged("ContactId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactIdName {
            get {
                return this.ContactIdNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactIdNameField, value) != true)) {
                    this.ContactIdNameField = value;
                    this.RaisePropertyChanged("ContactIdName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contactnumber {
            get {
                return this.ContactnumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactnumberField, value) != true)) {
                    this.ContactnumberField = value;
                    this.RaisePropertyChanged("Contactnumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Creditcardmask {
            get {
                return this.CreditcardmaskField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditcardmaskField, value) != true)) {
                    this.CreditcardmaskField = value;
                    this.RaisePropertyChanged("Creditcardmask");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Failedattemptstochargemoney {
            get {
                return this.FailedattemptstochargemoneyField;
            }
            set {
                if ((object.ReferenceEquals(this.FailedattemptstochargemoneyField, value) != true)) {
                    this.FailedattemptstochargemoneyField = value;
                    this.RaisePropertyChanged("Failedattemptstochargemoney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumberOfZones {
            get {
                return this.NumberOfZonesField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberOfZonesField, value) != true)) {
                    this.NumberOfZonesField = value;
                    this.RaisePropertyChanged("NumberOfZones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PeriodeicCardType {
            get {
                return this.PeriodeicCardTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PeriodeicCardTypeField, value) != true)) {
                    this.PeriodeicCardTypeField = value;
                    this.RaisePropertyChanged("PeriodeicCardType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateCode {
            get {
                return this.StateCodeField;
            }
            set {
                if ((this.StateCodeField.Equals(value) != true)) {
                    this.StateCodeField = value;
                    this.RaisePropertyChanged("StateCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TravelCardID {
            get {
                return this.TravelCardIDField;
            }
            set {
                if ((this.TravelCardIDField.Equals(value) != true)) {
                    this.TravelCardIDField = value;
                    this.RaisePropertyChanged("TravelCardID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TravelCardName {
            get {
                return this.TravelCardNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TravelCardNameField, value) != true)) {
                    this.TravelCardNameField = value;
                    this.RaisePropertyChanged("TravelCardName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValidFrom {
            get {
                return this.ValidFromField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidFromField, value) != true)) {
                    this.ValidFromField = value;
                    this.RaisePropertyChanged("ValidFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValidTo {
            get {
                return this.ValidToField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidToField, value) != true)) {
                    this.ValidToField = value;
                    this.RaisePropertyChanged("ValidTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value_card_type {
            get {
                return this.Value_card_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.Value_card_typeField, value) != true)) {
                    this.Value_card_typeField = value;
                    this.RaisePropertyChanged("Value_card_type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCardTransactionsResponse", Namespace="http://schemas.datacontract.org/2004/07/CGIXrmTravelCard")]
    public partial class GetCardTransactionsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ErrorMessageField;
        
        private string TransactionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Transactions {
            get {
                return this.TransactionsField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionsField, value) != true)) {
                    this.TransactionsField = value;
                    this.RaisePropertyChanged("Transactions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetZoneNamesResponse", Namespace="http://schemas.datacontract.org/2004/07/CGIXrmTravelCard")]
    public partial class GetZoneNamesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ErrorMessageField;
        
        private System.Collections.ObjectModel.ObservableCollection<CRM.GetBIFFTransactions.TravelCardService.Zone> ZonesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<CRM.GetBIFFTransactions.TravelCardService.Zone> Zones {
            get {
                return this.ZonesField;
            }
            set {
                if ((object.ReferenceEquals(this.ZonesField, value) != true)) {
                    this.ZonesField = value;
                    this.RaisePropertyChanged("Zones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zone", Namespace="http://schemas.datacontract.org/2004/07/CGIXrmTravelCard")]
    public partial class Zone : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ZoneIdField;
        
        private string ZoneNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZoneId {
            get {
                return this.ZoneIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ZoneIdField, value) != true)) {
                    this.ZoneIdField = value;
                    this.RaisePropertyChanged("ZoneId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZoneName {
            get {
                return this.ZoneNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ZoneNameField, value) != true)) {
                    this.ZoneNameField = value;
                    this.RaisePropertyChanged("ZoneName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTravelCardTransactionsResponse", Namespace="http://schemas.datacontract.org/2004/07/CGIXrmTravelCard")]
    public partial class GetTravelCardTransactionsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ErrorMessageField;
        
        private System.Collections.ObjectModel.ObservableCollection<CRM.GetBIFFTransactions.TravelCardService.TravelCardTransaction> TravelCardTransactionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<CRM.GetBIFFTransactions.TravelCardService.TravelCardTransaction> TravelCardTransactions {
            get {
                return this.TravelCardTransactionsField;
            }
            set {
                if ((object.ReferenceEquals(this.TravelCardTransactionsField, value) != true)) {
                    this.TravelCardTransactionsField = value;
                    this.RaisePropertyChanged("TravelCardTransactions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TravelCardTransaction", Namespace="http://schemas.datacontract.org/2004/07/CGIXrmTravelCard")]
    public partial class TravelCardTransaction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AmountField;
        
        private System.Nullable<System.Guid> CardIdField;
        
        private string CardSectField;
        
        private System.Nullable<System.Guid> CaseIdField;
        
        private string CurrencyField;
        
        private string DateField;
        
        private string DeviceIDField;
        
        private string NameField;
        
        private string OrigZoneField;
        
        private string OrigZoneNameField;
        
        private string RecTypeField;
        
        private string RouteField;
        
        private string TimeField;
        
        private System.Nullable<System.Guid> TransactionidField;
        
        private string TravelCardField;
        
        private string TxnTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountField, value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> CardId {
            get {
                return this.CardIdField;
            }
            set {
                if ((this.CardIdField.Equals(value) != true)) {
                    this.CardIdField = value;
                    this.RaisePropertyChanged("CardId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardSect {
            get {
                return this.CardSectField;
            }
            set {
                if ((object.ReferenceEquals(this.CardSectField, value) != true)) {
                    this.CardSectField = value;
                    this.RaisePropertyChanged("CardSect");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> CaseId {
            get {
                return this.CaseIdField;
            }
            set {
                if ((this.CaseIdField.Equals(value) != true)) {
                    this.CaseIdField = value;
                    this.RaisePropertyChanged("CaseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceID {
            get {
                return this.DeviceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceIDField, value) != true)) {
                    this.DeviceIDField = value;
                    this.RaisePropertyChanged("DeviceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrigZone {
            get {
                return this.OrigZoneField;
            }
            set {
                if ((object.ReferenceEquals(this.OrigZoneField, value) != true)) {
                    this.OrigZoneField = value;
                    this.RaisePropertyChanged("OrigZone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrigZoneName {
            get {
                return this.OrigZoneNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrigZoneNameField, value) != true)) {
                    this.OrigZoneNameField = value;
                    this.RaisePropertyChanged("OrigZoneName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecType {
            get {
                return this.RecTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.RecTypeField, value) != true)) {
                    this.RecTypeField = value;
                    this.RaisePropertyChanged("RecType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Route {
            get {
                return this.RouteField;
            }
            set {
                if ((object.ReferenceEquals(this.RouteField, value) != true)) {
                    this.RouteField = value;
                    this.RaisePropertyChanged("Route");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Time {
            get {
                return this.TimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeField, value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> Transactionid {
            get {
                return this.TransactionidField;
            }
            set {
                if ((this.TransactionidField.Equals(value) != true)) {
                    this.TransactionidField = value;
                    this.RaisePropertyChanged("Transactionid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TravelCard {
            get {
                return this.TravelCardField;
            }
            set {
                if ((object.ReferenceEquals(this.TravelCardField, value) != true)) {
                    this.TravelCardField = value;
                    this.RaisePropertyChanged("TravelCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TxnType {
            get {
                return this.TxnTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TxnTypeField, value) != true)) {
                    this.TxnTypeField = value;
                    this.RaisePropertyChanged("TxnType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOutstandingChargesResponse", Namespace="http://schemas.datacontract.org/2004/07/CGIXrmTravelCard")]
    public partial class GetOutstandingChargesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ErrorMessageField;
        
        private string OutstandingChargesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutstandingCharges {
            get {
                return this.OutstandingChargesField;
            }
            set {
                if ((object.ReferenceEquals(this.OutstandingChargesField, value) != true)) {
                    this.OutstandingChargesField = value;
                    this.RaisePropertyChanged("OutstandingCharges");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RechargeCardResponse", Namespace="http://schemas.datacontract.org/2004/07/CGIXrmTravelCard")]
    public partial class RechargeCardResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ErrorMessageField;
        
        private string RechargeCardField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RechargeCard {
            get {
                return this.RechargeCardField;
            }
            set {
                if ((object.ReferenceEquals(this.RechargeCardField, value) != true)) {
                    this.RechargeCardField = value;
                    this.RaisePropertyChanged("RechargeCard");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TravelCardService.ITravelCard")]
    public interface ITravelCard {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITravelCard/GetCardDetails", ReplyAction="http://tempuri.org/ITravelCard/GetCardDetailsResponse")]
        System.IAsyncResult BeginGetCardDetails(string cardnumber, System.AsyncCallback callback, object asyncState);
        
        CRM.GetBIFFTransactions.TravelCardService.GetCardDetailsResponse EndGetCardDetails(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITravelCard/GetCardFromCRM", ReplyAction="http://tempuri.org/ITravelCard/GetCardFromCRMResponse")]
        System.IAsyncResult BeginGetCardFromCRM(string cardnumber, System.AsyncCallback callback, object asyncState);
        
        CRM.GetBIFFTransactions.TravelCardService.GetCRMCardDetailsResponse EndGetCardFromCRM(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITravelCard/GetCardFromCRMExtended", ReplyAction="http://tempuri.org/ITravelCard/GetCardFromCRMExtendedResponse")]
        System.IAsyncResult BeginGetCardFromCRMExtended(string cardnumber, System.AsyncCallback callback, object asyncState);
        
        CRM.GetBIFFTransactions.TravelCardService.GetCRMCardDetailsResponse EndGetCardFromCRMExtended(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITravelCard/GetCardTransactions", ReplyAction="http://tempuri.org/ITravelCard/GetCardTransactionsResponse")]
        System.IAsyncResult BeginGetCardTransactions(string cardnumber, string maxtrasactions, string datefrom, string dateto, System.AsyncCallback callback, object asyncState);
        
        CRM.GetBIFFTransactions.TravelCardService.GetCardTransactionsResponse EndGetCardTransactions(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITravelCard/GetZoneNames", ReplyAction="http://tempuri.org/ITravelCard/GetZoneNamesResponse")]
        System.IAsyncResult BeginGetZoneNames(System.AsyncCallback callback, object asyncState);
        
        CRM.GetBIFFTransactions.TravelCardService.GetZoneNamesResponse EndGetZoneNames(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITravelCard/GetTravelCardTransactions", ReplyAction="http://tempuri.org/ITravelCard/GetTravelCardTransactionsResponse")]
        System.IAsyncResult BeginGetTravelCardTransactions(string travelcardtransactionid, System.AsyncCallback callback, object asyncState);
        
        CRM.GetBIFFTransactions.TravelCardService.GetTravelCardTransactionsResponse EndGetTravelCardTransactions(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITravelCard/GetGetOutstandingCharges", ReplyAction="http://tempuri.org/ITravelCard/GetGetOutstandingChargesResponse")]
        System.IAsyncResult BeginGetGetOutstandingCharges(string cardnumber, System.AsyncCallback callback, object asyncState);
        
        CRM.GetBIFFTransactions.TravelCardService.GetOutstandingChargesResponse EndGetGetOutstandingCharges(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITravelCard/RechargeCard", ReplyAction="http://tempuri.org/ITravelCard/RechargeCardResponse")]
        System.IAsyncResult BeginRechargeCard(string cardnumber, System.AsyncCallback callback, object asyncState);
        
        CRM.GetBIFFTransactions.TravelCardService.RechargeCardResponse EndRechargeCard(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITravelCardChannel : CRM.GetBIFFTransactions.TravelCardService.ITravelCard, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCardDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCardDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CRM.GetBIFFTransactions.TravelCardService.GetCardDetailsResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CRM.GetBIFFTransactions.TravelCardService.GetCardDetailsResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCardFromCRMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCardFromCRMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CRM.GetBIFFTransactions.TravelCardService.GetCRMCardDetailsResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CRM.GetBIFFTransactions.TravelCardService.GetCRMCardDetailsResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCardFromCRMExtendedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCardFromCRMExtendedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CRM.GetBIFFTransactions.TravelCardService.GetCRMCardDetailsResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CRM.GetBIFFTransactions.TravelCardService.GetCRMCardDetailsResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCardTransactionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCardTransactionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CRM.GetBIFFTransactions.TravelCardService.GetCardTransactionsResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CRM.GetBIFFTransactions.TravelCardService.GetCardTransactionsResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetZoneNamesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetZoneNamesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CRM.GetBIFFTransactions.TravelCardService.GetZoneNamesResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CRM.GetBIFFTransactions.TravelCardService.GetZoneNamesResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTravelCardTransactionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTravelCardTransactionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CRM.GetBIFFTransactions.TravelCardService.GetTravelCardTransactionsResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CRM.GetBIFFTransactions.TravelCardService.GetTravelCardTransactionsResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetGetOutstandingChargesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetGetOutstandingChargesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CRM.GetBIFFTransactions.TravelCardService.GetOutstandingChargesResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CRM.GetBIFFTransactions.TravelCardService.GetOutstandingChargesResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RechargeCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RechargeCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CRM.GetBIFFTransactions.TravelCardService.RechargeCardResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CRM.GetBIFFTransactions.TravelCardService.RechargeCardResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TravelCardClient : System.ServiceModel.ClientBase<CRM.GetBIFFTransactions.TravelCardService.ITravelCard>, CRM.GetBIFFTransactions.TravelCardService.ITravelCard {
        
        private BeginOperationDelegate onBeginGetCardDetailsDelegate;
        
        private EndOperationDelegate onEndGetCardDetailsDelegate;
        
        private System.Threading.SendOrPostCallback onGetCardDetailsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCardFromCRMDelegate;
        
        private EndOperationDelegate onEndGetCardFromCRMDelegate;
        
        private System.Threading.SendOrPostCallback onGetCardFromCRMCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCardFromCRMExtendedDelegate;
        
        private EndOperationDelegate onEndGetCardFromCRMExtendedDelegate;
        
        private System.Threading.SendOrPostCallback onGetCardFromCRMExtendedCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCardTransactionsDelegate;
        
        private EndOperationDelegate onEndGetCardTransactionsDelegate;
        
        private System.Threading.SendOrPostCallback onGetCardTransactionsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetZoneNamesDelegate;
        
        private EndOperationDelegate onEndGetZoneNamesDelegate;
        
        private System.Threading.SendOrPostCallback onGetZoneNamesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTravelCardTransactionsDelegate;
        
        private EndOperationDelegate onEndGetTravelCardTransactionsDelegate;
        
        private System.Threading.SendOrPostCallback onGetTravelCardTransactionsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetGetOutstandingChargesDelegate;
        
        private EndOperationDelegate onEndGetGetOutstandingChargesDelegate;
        
        private System.Threading.SendOrPostCallback onGetGetOutstandingChargesCompletedDelegate;
        
        private BeginOperationDelegate onBeginRechargeCardDelegate;
        
        private EndOperationDelegate onEndRechargeCardDelegate;
        
        private System.Threading.SendOrPostCallback onRechargeCardCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public TravelCardClient() {
        }
        
        public TravelCardClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TravelCardClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TravelCardClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TravelCardClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetCardDetailsCompletedEventArgs> GetCardDetailsCompleted;
        
        public event System.EventHandler<GetCardFromCRMCompletedEventArgs> GetCardFromCRMCompleted;
        
        public event System.EventHandler<GetCardFromCRMExtendedCompletedEventArgs> GetCardFromCRMExtendedCompleted;
        
        public event System.EventHandler<GetCardTransactionsCompletedEventArgs> GetCardTransactionsCompleted;
        
        public event System.EventHandler<GetZoneNamesCompletedEventArgs> GetZoneNamesCompleted;
        
        public event System.EventHandler<GetTravelCardTransactionsCompletedEventArgs> GetTravelCardTransactionsCompleted;
        
        public event System.EventHandler<GetGetOutstandingChargesCompletedEventArgs> GetGetOutstandingChargesCompleted;
        
        public event System.EventHandler<RechargeCardCompletedEventArgs> RechargeCardCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CRM.GetBIFFTransactions.TravelCardService.ITravelCard.BeginGetCardDetails(string cardnumber, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCardDetails(cardnumber, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.GetBIFFTransactions.TravelCardService.GetCardDetailsResponse CRM.GetBIFFTransactions.TravelCardService.ITravelCard.EndGetCardDetails(System.IAsyncResult result) {
            return base.Channel.EndGetCardDetails(result);
        }
        
        private System.IAsyncResult OnBeginGetCardDetails(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string cardnumber = ((string)(inValues[0]));
            return ((CRM.GetBIFFTransactions.TravelCardService.ITravelCard)(this)).BeginGetCardDetails(cardnumber, callback, asyncState);
        }
        
        private object[] OnEndGetCardDetails(System.IAsyncResult result) {
            CRM.GetBIFFTransactions.TravelCardService.GetCardDetailsResponse retVal = ((CRM.GetBIFFTransactions.TravelCardService.ITravelCard)(this)).EndGetCardDetails(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCardDetailsCompleted(object state) {
            if ((this.GetCardDetailsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCardDetailsCompleted(this, new GetCardDetailsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCardDetailsAsync(string cardnumber) {
            this.GetCardDetailsAsync(cardnumber, null);
        }
        
        public void GetCardDetailsAsync(string cardnumber, object userState) {
            if ((this.onBeginGetCardDetailsDelegate == null)) {
                this.onBeginGetCardDetailsDelegate = new BeginOperationDelegate(this.OnBeginGetCardDetails);
            }
            if ((this.onEndGetCardDetailsDelegate == null)) {
                this.onEndGetCardDetailsDelegate = new EndOperationDelegate(this.OnEndGetCardDetails);
            }
            if ((this.onGetCardDetailsCompletedDelegate == null)) {
                this.onGetCardDetailsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCardDetailsCompleted);
            }
            base.InvokeAsync(this.onBeginGetCardDetailsDelegate, new object[] {
                        cardnumber}, this.onEndGetCardDetailsDelegate, this.onGetCardDetailsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CRM.GetBIFFTransactions.TravelCardService.ITravelCard.BeginGetCardFromCRM(string cardnumber, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCardFromCRM(cardnumber, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.GetBIFFTransactions.TravelCardService.GetCRMCardDetailsResponse CRM.GetBIFFTransactions.TravelCardService.ITravelCard.EndGetCardFromCRM(System.IAsyncResult result) {
            return base.Channel.EndGetCardFromCRM(result);
        }
        
        private System.IAsyncResult OnBeginGetCardFromCRM(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string cardnumber = ((string)(inValues[0]));
            return ((CRM.GetBIFFTransactions.TravelCardService.ITravelCard)(this)).BeginGetCardFromCRM(cardnumber, callback, asyncState);
        }
        
        private object[] OnEndGetCardFromCRM(System.IAsyncResult result) {
            CRM.GetBIFFTransactions.TravelCardService.GetCRMCardDetailsResponse retVal = ((CRM.GetBIFFTransactions.TravelCardService.ITravelCard)(this)).EndGetCardFromCRM(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCardFromCRMCompleted(object state) {
            if ((this.GetCardFromCRMCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCardFromCRMCompleted(this, new GetCardFromCRMCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCardFromCRMAsync(string cardnumber) {
            this.GetCardFromCRMAsync(cardnumber, null);
        }
        
        public void GetCardFromCRMAsync(string cardnumber, object userState) {
            if ((this.onBeginGetCardFromCRMDelegate == null)) {
                this.onBeginGetCardFromCRMDelegate = new BeginOperationDelegate(this.OnBeginGetCardFromCRM);
            }
            if ((this.onEndGetCardFromCRMDelegate == null)) {
                this.onEndGetCardFromCRMDelegate = new EndOperationDelegate(this.OnEndGetCardFromCRM);
            }
            if ((this.onGetCardFromCRMCompletedDelegate == null)) {
                this.onGetCardFromCRMCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCardFromCRMCompleted);
            }
            base.InvokeAsync(this.onBeginGetCardFromCRMDelegate, new object[] {
                        cardnumber}, this.onEndGetCardFromCRMDelegate, this.onGetCardFromCRMCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CRM.GetBIFFTransactions.TravelCardService.ITravelCard.BeginGetCardFromCRMExtended(string cardnumber, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCardFromCRMExtended(cardnumber, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.GetBIFFTransactions.TravelCardService.GetCRMCardDetailsResponse CRM.GetBIFFTransactions.TravelCardService.ITravelCard.EndGetCardFromCRMExtended(System.IAsyncResult result) {
            return base.Channel.EndGetCardFromCRMExtended(result);
        }
        
        private System.IAsyncResult OnBeginGetCardFromCRMExtended(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string cardnumber = ((string)(inValues[0]));
            return ((CRM.GetBIFFTransactions.TravelCardService.ITravelCard)(this)).BeginGetCardFromCRMExtended(cardnumber, callback, asyncState);
        }
        
        private object[] OnEndGetCardFromCRMExtended(System.IAsyncResult result) {
            CRM.GetBIFFTransactions.TravelCardService.GetCRMCardDetailsResponse retVal = ((CRM.GetBIFFTransactions.TravelCardService.ITravelCard)(this)).EndGetCardFromCRMExtended(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCardFromCRMExtendedCompleted(object state) {
            if ((this.GetCardFromCRMExtendedCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCardFromCRMExtendedCompleted(this, new GetCardFromCRMExtendedCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCardFromCRMExtendedAsync(string cardnumber) {
            this.GetCardFromCRMExtendedAsync(cardnumber, null);
        }
        
        public void GetCardFromCRMExtendedAsync(string cardnumber, object userState) {
            if ((this.onBeginGetCardFromCRMExtendedDelegate == null)) {
                this.onBeginGetCardFromCRMExtendedDelegate = new BeginOperationDelegate(this.OnBeginGetCardFromCRMExtended);
            }
            if ((this.onEndGetCardFromCRMExtendedDelegate == null)) {
                this.onEndGetCardFromCRMExtendedDelegate = new EndOperationDelegate(this.OnEndGetCardFromCRMExtended);
            }
            if ((this.onGetCardFromCRMExtendedCompletedDelegate == null)) {
                this.onGetCardFromCRMExtendedCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCardFromCRMExtendedCompleted);
            }
            base.InvokeAsync(this.onBeginGetCardFromCRMExtendedDelegate, new object[] {
                        cardnumber}, this.onEndGetCardFromCRMExtendedDelegate, this.onGetCardFromCRMExtendedCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CRM.GetBIFFTransactions.TravelCardService.ITravelCard.BeginGetCardTransactions(string cardnumber, string maxtrasactions, string datefrom, string dateto, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCardTransactions(cardnumber, maxtrasactions, datefrom, dateto, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.GetBIFFTransactions.TravelCardService.GetCardTransactionsResponse CRM.GetBIFFTransactions.TravelCardService.ITravelCard.EndGetCardTransactions(System.IAsyncResult result) {
            return base.Channel.EndGetCardTransactions(result);
        }
        
        private System.IAsyncResult OnBeginGetCardTransactions(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string cardnumber = ((string)(inValues[0]));
            string maxtrasactions = ((string)(inValues[1]));
            string datefrom = ((string)(inValues[2]));
            string dateto = ((string)(inValues[3]));
            return ((CRM.GetBIFFTransactions.TravelCardService.ITravelCard)(this)).BeginGetCardTransactions(cardnumber, maxtrasactions, datefrom, dateto, callback, asyncState);
        }
        
        private object[] OnEndGetCardTransactions(System.IAsyncResult result) {
            CRM.GetBIFFTransactions.TravelCardService.GetCardTransactionsResponse retVal = ((CRM.GetBIFFTransactions.TravelCardService.ITravelCard)(this)).EndGetCardTransactions(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCardTransactionsCompleted(object state) {
            if ((this.GetCardTransactionsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCardTransactionsCompleted(this, new GetCardTransactionsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCardTransactionsAsync(string cardnumber, string maxtrasactions, string datefrom, string dateto) {
            this.GetCardTransactionsAsync(cardnumber, maxtrasactions, datefrom, dateto, null);
        }
        
        public void GetCardTransactionsAsync(string cardnumber, string maxtrasactions, string datefrom, string dateto, object userState) {
            if ((this.onBeginGetCardTransactionsDelegate == null)) {
                this.onBeginGetCardTransactionsDelegate = new BeginOperationDelegate(this.OnBeginGetCardTransactions);
            }
            if ((this.onEndGetCardTransactionsDelegate == null)) {
                this.onEndGetCardTransactionsDelegate = new EndOperationDelegate(this.OnEndGetCardTransactions);
            }
            if ((this.onGetCardTransactionsCompletedDelegate == null)) {
                this.onGetCardTransactionsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCardTransactionsCompleted);
            }
            base.InvokeAsync(this.onBeginGetCardTransactionsDelegate, new object[] {
                        cardnumber,
                        maxtrasactions,
                        datefrom,
                        dateto}, this.onEndGetCardTransactionsDelegate, this.onGetCardTransactionsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CRM.GetBIFFTransactions.TravelCardService.ITravelCard.BeginGetZoneNames(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetZoneNames(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.GetBIFFTransactions.TravelCardService.GetZoneNamesResponse CRM.GetBIFFTransactions.TravelCardService.ITravelCard.EndGetZoneNames(System.IAsyncResult result) {
            return base.Channel.EndGetZoneNames(result);
        }
        
        private System.IAsyncResult OnBeginGetZoneNames(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((CRM.GetBIFFTransactions.TravelCardService.ITravelCard)(this)).BeginGetZoneNames(callback, asyncState);
        }
        
        private object[] OnEndGetZoneNames(System.IAsyncResult result) {
            CRM.GetBIFFTransactions.TravelCardService.GetZoneNamesResponse retVal = ((CRM.GetBIFFTransactions.TravelCardService.ITravelCard)(this)).EndGetZoneNames(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetZoneNamesCompleted(object state) {
            if ((this.GetZoneNamesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetZoneNamesCompleted(this, new GetZoneNamesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetZoneNamesAsync() {
            this.GetZoneNamesAsync(null);
        }
        
        public void GetZoneNamesAsync(object userState) {
            if ((this.onBeginGetZoneNamesDelegate == null)) {
                this.onBeginGetZoneNamesDelegate = new BeginOperationDelegate(this.OnBeginGetZoneNames);
            }
            if ((this.onEndGetZoneNamesDelegate == null)) {
                this.onEndGetZoneNamesDelegate = new EndOperationDelegate(this.OnEndGetZoneNames);
            }
            if ((this.onGetZoneNamesCompletedDelegate == null)) {
                this.onGetZoneNamesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetZoneNamesCompleted);
            }
            base.InvokeAsync(this.onBeginGetZoneNamesDelegate, null, this.onEndGetZoneNamesDelegate, this.onGetZoneNamesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CRM.GetBIFFTransactions.TravelCardService.ITravelCard.BeginGetTravelCardTransactions(string travelcardtransactionid, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTravelCardTransactions(travelcardtransactionid, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.GetBIFFTransactions.TravelCardService.GetTravelCardTransactionsResponse CRM.GetBIFFTransactions.TravelCardService.ITravelCard.EndGetTravelCardTransactions(System.IAsyncResult result) {
            return base.Channel.EndGetTravelCardTransactions(result);
        }
        
        private System.IAsyncResult OnBeginGetTravelCardTransactions(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string travelcardtransactionid = ((string)(inValues[0]));
            return ((CRM.GetBIFFTransactions.TravelCardService.ITravelCard)(this)).BeginGetTravelCardTransactions(travelcardtransactionid, callback, asyncState);
        }
        
        private object[] OnEndGetTravelCardTransactions(System.IAsyncResult result) {
            CRM.GetBIFFTransactions.TravelCardService.GetTravelCardTransactionsResponse retVal = ((CRM.GetBIFFTransactions.TravelCardService.ITravelCard)(this)).EndGetTravelCardTransactions(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTravelCardTransactionsCompleted(object state) {
            if ((this.GetTravelCardTransactionsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTravelCardTransactionsCompleted(this, new GetTravelCardTransactionsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTravelCardTransactionsAsync(string travelcardtransactionid) {
            this.GetTravelCardTransactionsAsync(travelcardtransactionid, null);
        }
        
        public void GetTravelCardTransactionsAsync(string travelcardtransactionid, object userState) {
            if ((this.onBeginGetTravelCardTransactionsDelegate == null)) {
                this.onBeginGetTravelCardTransactionsDelegate = new BeginOperationDelegate(this.OnBeginGetTravelCardTransactions);
            }
            if ((this.onEndGetTravelCardTransactionsDelegate == null)) {
                this.onEndGetTravelCardTransactionsDelegate = new EndOperationDelegate(this.OnEndGetTravelCardTransactions);
            }
            if ((this.onGetTravelCardTransactionsCompletedDelegate == null)) {
                this.onGetTravelCardTransactionsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTravelCardTransactionsCompleted);
            }
            base.InvokeAsync(this.onBeginGetTravelCardTransactionsDelegate, new object[] {
                        travelcardtransactionid}, this.onEndGetTravelCardTransactionsDelegate, this.onGetTravelCardTransactionsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CRM.GetBIFFTransactions.TravelCardService.ITravelCard.BeginGetGetOutstandingCharges(string cardnumber, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetGetOutstandingCharges(cardnumber, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.GetBIFFTransactions.TravelCardService.GetOutstandingChargesResponse CRM.GetBIFFTransactions.TravelCardService.ITravelCard.EndGetGetOutstandingCharges(System.IAsyncResult result) {
            return base.Channel.EndGetGetOutstandingCharges(result);
        }
        
        private System.IAsyncResult OnBeginGetGetOutstandingCharges(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string cardnumber = ((string)(inValues[0]));
            return ((CRM.GetBIFFTransactions.TravelCardService.ITravelCard)(this)).BeginGetGetOutstandingCharges(cardnumber, callback, asyncState);
        }
        
        private object[] OnEndGetGetOutstandingCharges(System.IAsyncResult result) {
            CRM.GetBIFFTransactions.TravelCardService.GetOutstandingChargesResponse retVal = ((CRM.GetBIFFTransactions.TravelCardService.ITravelCard)(this)).EndGetGetOutstandingCharges(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetGetOutstandingChargesCompleted(object state) {
            if ((this.GetGetOutstandingChargesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetGetOutstandingChargesCompleted(this, new GetGetOutstandingChargesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetGetOutstandingChargesAsync(string cardnumber) {
            this.GetGetOutstandingChargesAsync(cardnumber, null);
        }
        
        public void GetGetOutstandingChargesAsync(string cardnumber, object userState) {
            if ((this.onBeginGetGetOutstandingChargesDelegate == null)) {
                this.onBeginGetGetOutstandingChargesDelegate = new BeginOperationDelegate(this.OnBeginGetGetOutstandingCharges);
            }
            if ((this.onEndGetGetOutstandingChargesDelegate == null)) {
                this.onEndGetGetOutstandingChargesDelegate = new EndOperationDelegate(this.OnEndGetGetOutstandingCharges);
            }
            if ((this.onGetGetOutstandingChargesCompletedDelegate == null)) {
                this.onGetGetOutstandingChargesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetGetOutstandingChargesCompleted);
            }
            base.InvokeAsync(this.onBeginGetGetOutstandingChargesDelegate, new object[] {
                        cardnumber}, this.onEndGetGetOutstandingChargesDelegate, this.onGetGetOutstandingChargesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CRM.GetBIFFTransactions.TravelCardService.ITravelCard.BeginRechargeCard(string cardnumber, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRechargeCard(cardnumber, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.GetBIFFTransactions.TravelCardService.RechargeCardResponse CRM.GetBIFFTransactions.TravelCardService.ITravelCard.EndRechargeCard(System.IAsyncResult result) {
            return base.Channel.EndRechargeCard(result);
        }
        
        private System.IAsyncResult OnBeginRechargeCard(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string cardnumber = ((string)(inValues[0]));
            return ((CRM.GetBIFFTransactions.TravelCardService.ITravelCard)(this)).BeginRechargeCard(cardnumber, callback, asyncState);
        }
        
        private object[] OnEndRechargeCard(System.IAsyncResult result) {
            CRM.GetBIFFTransactions.TravelCardService.RechargeCardResponse retVal = ((CRM.GetBIFFTransactions.TravelCardService.ITravelCard)(this)).EndRechargeCard(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRechargeCardCompleted(object state) {
            if ((this.RechargeCardCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RechargeCardCompleted(this, new RechargeCardCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RechargeCardAsync(string cardnumber) {
            this.RechargeCardAsync(cardnumber, null);
        }
        
        public void RechargeCardAsync(string cardnumber, object userState) {
            if ((this.onBeginRechargeCardDelegate == null)) {
                this.onBeginRechargeCardDelegate = new BeginOperationDelegate(this.OnBeginRechargeCard);
            }
            if ((this.onEndRechargeCardDelegate == null)) {
                this.onEndRechargeCardDelegate = new EndOperationDelegate(this.OnEndRechargeCard);
            }
            if ((this.onRechargeCardCompletedDelegate == null)) {
                this.onRechargeCardCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRechargeCardCompleted);
            }
            base.InvokeAsync(this.onBeginRechargeCardDelegate, new object[] {
                        cardnumber}, this.onEndRechargeCardDelegate, this.onRechargeCardCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override CRM.GetBIFFTransactions.TravelCardService.ITravelCard CreateChannel() {
            return new TravelCardClientChannel(this);
        }
        
        private class TravelCardClientChannel : ChannelBase<CRM.GetBIFFTransactions.TravelCardService.ITravelCard>, CRM.GetBIFFTransactions.TravelCardService.ITravelCard {
            
            public TravelCardClientChannel(System.ServiceModel.ClientBase<CRM.GetBIFFTransactions.TravelCardService.ITravelCard> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetCardDetails(string cardnumber, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = cardnumber;
                System.IAsyncResult _result = base.BeginInvoke("GetCardDetails", _args, callback, asyncState);
                return _result;
            }
            
            public CRM.GetBIFFTransactions.TravelCardService.GetCardDetailsResponse EndGetCardDetails(System.IAsyncResult result) {
                object[] _args = new object[0];
                CRM.GetBIFFTransactions.TravelCardService.GetCardDetailsResponse _result = ((CRM.GetBIFFTransactions.TravelCardService.GetCardDetailsResponse)(base.EndInvoke("GetCardDetails", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetCardFromCRM(string cardnumber, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = cardnumber;
                System.IAsyncResult _result = base.BeginInvoke("GetCardFromCRM", _args, callback, asyncState);
                return _result;
            }
            
            public CRM.GetBIFFTransactions.TravelCardService.GetCRMCardDetailsResponse EndGetCardFromCRM(System.IAsyncResult result) {
                object[] _args = new object[0];
                CRM.GetBIFFTransactions.TravelCardService.GetCRMCardDetailsResponse _result = ((CRM.GetBIFFTransactions.TravelCardService.GetCRMCardDetailsResponse)(base.EndInvoke("GetCardFromCRM", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetCardFromCRMExtended(string cardnumber, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = cardnumber;
                System.IAsyncResult _result = base.BeginInvoke("GetCardFromCRMExtended", _args, callback, asyncState);
                return _result;
            }
            
            public CRM.GetBIFFTransactions.TravelCardService.GetCRMCardDetailsResponse EndGetCardFromCRMExtended(System.IAsyncResult result) {
                object[] _args = new object[0];
                CRM.GetBIFFTransactions.TravelCardService.GetCRMCardDetailsResponse _result = ((CRM.GetBIFFTransactions.TravelCardService.GetCRMCardDetailsResponse)(base.EndInvoke("GetCardFromCRMExtended", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetCardTransactions(string cardnumber, string maxtrasactions, string datefrom, string dateto, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = cardnumber;
                _args[1] = maxtrasactions;
                _args[2] = datefrom;
                _args[3] = dateto;
                System.IAsyncResult _result = base.BeginInvoke("GetCardTransactions", _args, callback, asyncState);
                return _result;
            }
            
            public CRM.GetBIFFTransactions.TravelCardService.GetCardTransactionsResponse EndGetCardTransactions(System.IAsyncResult result) {
                object[] _args = new object[0];
                CRM.GetBIFFTransactions.TravelCardService.GetCardTransactionsResponse _result = ((CRM.GetBIFFTransactions.TravelCardService.GetCardTransactionsResponse)(base.EndInvoke("GetCardTransactions", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetZoneNames(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetZoneNames", _args, callback, asyncState);
                return _result;
            }
            
            public CRM.GetBIFFTransactions.TravelCardService.GetZoneNamesResponse EndGetZoneNames(System.IAsyncResult result) {
                object[] _args = new object[0];
                CRM.GetBIFFTransactions.TravelCardService.GetZoneNamesResponse _result = ((CRM.GetBIFFTransactions.TravelCardService.GetZoneNamesResponse)(base.EndInvoke("GetZoneNames", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetTravelCardTransactions(string travelcardtransactionid, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = travelcardtransactionid;
                System.IAsyncResult _result = base.BeginInvoke("GetTravelCardTransactions", _args, callback, asyncState);
                return _result;
            }
            
            public CRM.GetBIFFTransactions.TravelCardService.GetTravelCardTransactionsResponse EndGetTravelCardTransactions(System.IAsyncResult result) {
                object[] _args = new object[0];
                CRM.GetBIFFTransactions.TravelCardService.GetTravelCardTransactionsResponse _result = ((CRM.GetBIFFTransactions.TravelCardService.GetTravelCardTransactionsResponse)(base.EndInvoke("GetTravelCardTransactions", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetGetOutstandingCharges(string cardnumber, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = cardnumber;
                System.IAsyncResult _result = base.BeginInvoke("GetGetOutstandingCharges", _args, callback, asyncState);
                return _result;
            }
            
            public CRM.GetBIFFTransactions.TravelCardService.GetOutstandingChargesResponse EndGetGetOutstandingCharges(System.IAsyncResult result) {
                object[] _args = new object[0];
                CRM.GetBIFFTransactions.TravelCardService.GetOutstandingChargesResponse _result = ((CRM.GetBIFFTransactions.TravelCardService.GetOutstandingChargesResponse)(base.EndInvoke("GetGetOutstandingCharges", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRechargeCard(string cardnumber, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = cardnumber;
                System.IAsyncResult _result = base.BeginInvoke("RechargeCard", _args, callback, asyncState);
                return _result;
            }
            
            public CRM.GetBIFFTransactions.TravelCardService.RechargeCardResponse EndRechargeCard(System.IAsyncResult result) {
                object[] _args = new object[0];
                CRM.GetBIFFTransactions.TravelCardService.RechargeCardResponse _result = ((CRM.GetBIFFTransactions.TravelCardService.RechargeCardResponse)(base.EndInvoke("RechargeCard", _args, result)));
                return _result;
            }
        }
    }
}
