//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skanetrafiken.Crm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Skanetrafiken.Crm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kundtjänst får inte skapa redan validerad Kund (e-post 1).
        /// </summary>
        internal static string AdminCantCreateValidatedContact {
            get {
                return ResourceManager.GetString("AdminCantCreateValidatedContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kundtjänst får inte ändra en validerad e-postadress.
        /// </summary>
        internal static string AdminCantValidateContact {
            get {
                return ResourceManager.GetString("AdminCantValidateContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The agreement &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string AgreementNotFound {
            get {
                return ResourceManager.GetString("AgreementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Fältet CampaignId saknas.
        /// </summary>
        internal static string CampaignIdMissing {
            get {
                return ResourceManager.GetString("CampaignIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Kampanjen är inte komplett ännu. Fält som saknas: {0}.
        /// </summary>
        internal static string CampaignIncomplete {
            get {
                return ResourceManager.GetString("CampaignIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanjen är inte giltig för anmälan just nu..
        /// </summary>
        internal static string CampaignInvalid {
            get {
                return ResourceManager.GetString("CampaignInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Hittade ingen kampanj med ID: {}.
        /// </summary>
        internal static string CampaignMissing {
            get {
                return ResourceManager.GetString("CampaignMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunde inte skapa Kund.&lt;BR&gt;&lt;BR&gt;{0}.
        /// </summary>
        internal static string CouldNotCreateContact {
            get {
                return ResourceManager.GetString("CouldNotCreateContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunde inte skapa Kund. En kund med samma personnummer existerar redan..
        /// </summary>
        internal static string CouldNotCreateContactSocialSecurityConflict {
            get {
                return ResourceManager.GetString("CouldNotCreateContactSocialSecurityConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunde inte skapa Kund. En kund med samma e-postadress existerar redan..
        /// </summary>
        internal static string CouldNotCreateCustomerEmail {
            get {
                return ResourceManager.GetString("CouldNotCreateCustomerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunde inte skapa Kund. En kund med samma e-postadress och namn existerar redan..
        /// </summary>
        internal static string CouldNotCreateCustomerEmailName {
            get {
                return ResourceManager.GetString("CouldNotCreateCustomerEmailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunde inte skapa Kund. En validerad kund med samma personnummer existerar redan..
        /// </summary>
        internal static string CouldNotCreateCustomerSocSec {
            get {
                return ResourceManager.GetString("CouldNotCreateCustomerSocSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunde inte skapa Kund. En aktiv Kund med samma personnummer och/eller epostadress existerar redan..
        /// </summary>
        internal static string CouldNotCreateCustomerSocSecEmail {
            get {
                return ResourceManager.GetString("CouldNotCreateCustomerSocSecEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunde inte hitta ett land med ISO-kod {0}.
        /// </summary>
        internal static string CouldNotFindAValidCountryForISOCode {
            get {
                return ResourceManager.GetString("CouldNotFindAValidCountryForISOCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunde inte uppdatera Kund.&lt;BR&gt;&lt;BR&gt;{0}.
        /// </summary>
        internal static string CouldNotUpdateContact {
            get {
                return ResourceManager.GetString("CouldNotUpdateContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunde inte uppdatera Kund. En kund med samma personnummer existerar redan..
        /// </summary>
        internal static string CouldNotUpdateContactSocialSecurityConflict {
            get {
                return ResourceManager.GetString("CouldNotUpdateContactSocialSecurityConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunde inte uppdatera Kund. En kund med samma e-postadress och namn existerar redan..
        /// </summary>
        internal static string CouldNotUpdateCustomerEmail {
            get {
                return ResourceManager.GetString("CouldNotUpdateCustomerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunde inte verifiera denna Kund. En aktiv Kund med samma personnummer och/eller epostadress existerar redan.
        /// </summary>
        internal static string CouldNotVerifyCustomerSocSecEmail {
            get {
                return ResourceManager.GetString("CouldNotVerifyCustomerSocSecEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kund kan inte inaktiveras, har fortfarande kapital i MittKonto..
        /// </summary>
        internal static string CustomerHasBalanceMKL {
            get {
                return ResourceManager.GetString("CustomerHasBalanceMKL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default language &quot;{0}&quot; can not be found..
        /// </summary>
        internal static string DefaultLanguageNotFound {
            get {
                return ResourceManager.GetString("DefaultLanguageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialization of JSON failed..
        /// </summary>
        internal static string DeserializeJsonFailed {
            get {
                return ResourceManager.GetString("DeserializeJsonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen inkommande data funnen..
        /// </summary>
        internal static string IncomingDataCannotBeNull {
            get {
                return ResourceManager.GetString("IncomingDataCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interna konflikter i Databasen, vänligen kontakta administratör..
        /// </summary>
        internal static string InconsistencyInDatabase {
            get {
                return ResourceManager.GetString("InconsistencyInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template &quot;{0}&quot; could not be instantiated (as an email)..
        /// </summary>
        internal static string InstantiateTemplateFailed {
            get {
                return ResourceManager.GetString("InstantiateTemplateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogiltigt format på epostadress: {0}.
        /// </summary>
        internal static string InvalidFormatForEmail {
            get {
                return ResourceManager.GetString("InvalidFormatForEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogiltigt format på persondatum: {0}.
        /// </summary>
        internal static string InvalidFormatForIntenationalSocialSecurityNumber {
            get {
                return ResourceManager.GetString("InvalidFormatForIntenationalSocialSecurityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogiltigt format på mobilnummer: {0}.
        /// </summary>
        internal static string InvalidFormatForMobile {
            get {
                return ResourceManager.GetString("InvalidFormatForMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogiltigt format på postnummer: {0}.
        /// </summary>
        internal static string InvalidFormatForPostalCode {
            get {
                return ResourceManager.GetString("InvalidFormatForPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogiltigt format på personnummer: {0}.
        /// </summary>
        internal static string InvalidFormatForSocialSecurityNumber {
            get {
                return ResourceManager.GetString("InvalidFormatForSocialSecurityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogiltigt format på telefonnummer: {0}.
        /// </summary>
        internal static string InvalidFormatForTelephone {
            get {
                return ResourceManager.GetString("InvalidFormatForTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogiltigt format på ny epostadress: {0}.
        /// </summary>
        internal static string InvalidNewEmail {
            get {
                return ResourceManager.GetString("InvalidNewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogiltig informationskälla: {0}.
        /// </summary>
        internal static string InvalidSource {
            get {
                return ResourceManager.GetString("InvalidSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fält som saknas: .
        /// </summary>
        internal static string MissingFields {
            get {
                return ResourceManager.GetString("MissingFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inga fält saknas.
        /// </summary>
        internal static string NoMissingFields {
            get {
                return ResourceManager.GetString("NoMissingFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The opportunity &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string OpportunityNotFound {
            get {
                return ResourceManager.GetString("OpportunityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The opportunity presale &quot;{0}&quot; does not have a UoM or product..
        /// </summary>
        internal static string OpportunityPresaleUoMAndProductMissing {
            get {
                return ResourceManager.GetString("OpportunityPresaleUoMAndProductMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin can not be run without secure/unsecure configuration..
        /// </summary>
        internal static string PluginConfigurationMissing {
            get {
                return ResourceManager.GetString("PluginConfigurationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command field is missing for plugin trigger operation &quot;{0}&quot;..
        /// </summary>
        internal static string PluginTriggerCommandMissing {
            get {
                return ResourceManager.GetString("PluginTriggerCommandMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product &quot;{0}&quot; does not have a default UoM..
        /// </summary>
        internal static string ProductDefaultUomMissing {
            get {
                return ResourceManager.GetString("ProductDefaultUomMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quote &quot;{0}&quot; has been created..
        /// </summary>
        internal static string QuoteCreated {
            get {
                return ResourceManager.GetString("QuoteCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quote &quot;{0}&quot; has no rows..
        /// </summary>
        internal static string QuoteHasNoRows {
            get {
                return ResourceManager.GetString("QuoteHasNoRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote must have status Draft to be Won..
        /// </summary>
        internal static string QuoteMustHaveStatusDraftToBeWon {
            get {
                return ResourceManager.GetString("QuoteMustHaveStatusDraftToBeWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quote &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string QuoteNotFound {
            get {
                return ResourceManager.GetString("QuoteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quote &quot;{0}&quot; has been updated..
        /// </summary>
        internal static string QuoteUpdated {
            get {
                return ResourceManager.GetString("QuoteUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report full path is missing (ReportPath &quot;{0}&quot;, FileName = &quot;{0}&quot;)..
        /// </summary>
        internal static string ReportFullPathMissing {
            get {
                return ResourceManager.GetString("ReportFullPathMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string ReportNotFound {
            get {
                return ResourceManager.GetString("ReportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report service url is empty..
        /// </summary>
        internal static string ReportServiceUrlEmpty {
            get {
                return ResourceManager.GetString("ReportServiceUrlEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGOL käver antingen Personnummer eller e-postadress.
        /// </summary>
        internal static string RGOLNeedsEmailOrSocSecNr {
            get {
                return ResourceManager.GetString("RGOLNeedsEmailOrSocSecNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin can not be run without secure configuration..
        /// </summary>
        internal static string SecureConfigurationMissing {
            get {
                return ResourceManager.GetString("SecureConfigurationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inställning {0} saknas. Vänligen ange ett värde och försök igen..
        /// </summary>
        internal static string SettingsValueMissing {
            get {
                return ResourceManager.GetString("SettingsValueMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;SwedishSocialSecurityNumber&apos; must be specified..
        /// </summary>
        internal static string SwedishSocialSecurityNumberMustBeSpecified {
            get {
                return ResourceManager.GetString("SwedishSocialSecurityNumberMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system parameter &quot;{0}&quot; does not contain a value for &quot;{1}&quot;..
        /// </summary>
        internal static string SystemParameterFieldEmpty {
            get {
                return ResourceManager.GetString("SystemParameterFieldEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No system parameter entity can be found..
        /// </summary>
        internal static string SystemParameterNotFound {
            get {
                return ResourceManager.GetString("SystemParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denna kund kan inte inaktiveras då den har ett saldo i MittKonto.
        /// </summary>
        internal static string SystemUserNotAllowedToInactivate {
            get {
                return ResourceManager.GetString("SystemUserNotAllowedToInactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string TemplateNotFound {
            get {
                return ResourceManager.GetString("TemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin can not be run without unsecure configuration..
        /// </summary>
        internal static string UnsecureConfigurationMissing {
            get {
                return ResourceManager.GetString("UnsecureConfigurationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En giltig instans av entiteten &apos;Settings&apos; saknas. Vänligen kontakta administratör.
        /// </summary>
        internal static string ValidSettingsEntityMissing {
            get {
                return ResourceManager.GetString("ValidSettingsEntityMissing", resourceCulture);
            }
        }
    }
}
