//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Endeavor.Crm.CleanRecordsService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%APPDATA%\\Endeavor\\CloseCasesService.Credential.xml")]
        public string CredentialsFilePathCases {
            get {
                return ((string)(this["CredentialsFilePathCases"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0 0 19 ? * SAT *")]
        public string CloseCaseScheduleCronExpression {
            get {
                return ((string)(this["CloseCaseScheduleCronExpression"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2019-02-01T00:00:00Z")]
        public string StartDate {
            get {
                return ((string)(this["StartDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2019-02-03T00:00:00Z")]
        public string EndDate {
            get {
                return ((string)(this["EndDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2019-12-10T00:00:00Z")]
        public string SpecificDate {
            get {
                return ((string)(this["SpecificDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%APPDATA%\\Endeavor\\InactivateContactsService.Credential.xml")]
        public string CredentialsFilePathContacts {
            get {
                return ((string)(this["CredentialsFilePathContacts"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0 0 18 ? * SAT *")]
        public string InactivateContactsScheduleCronExpression {
            get {
                return ((string)(this["InactivateContactsScheduleCronExpression"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0 0 20 ? * SAT *")]
        public string DeleteAuditScheduleCronExpression {
            get {
                return ((string)(this["DeleteAuditScheduleCronExpression"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%APPDATA%\\Endeavor\\DeleteAuditsService.Credential.xml")]
        public string CredentialsFilePathAudits {
            get {
                return ((string)(this["CredentialsFilePathAudits"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%APPDATA%\\Endeavor\\InactivatePermitsService.Credential.xml")]
        public string CredentialsFilePathPermits
        {
            get
            {
                return ((string)(this["CredentialsFilePathPermits"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("* 2 ? * 1/1 *")]
        public string InactivatePermitsCronExpression
        {
            get
            {
                return ((string)(this["InactivatePermitsCronExpression"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int MonthsDelete {
            get {
                return ((int)(this["MonthsDelete"]));
            }
        }
    }
}
