CREATE TABLE [dbo].[cgi_refundBase] (
    [cgi_refundId]                 UNIQUEIDENTIFIER NOT NULL,
    [CreatedOn]                    DATETIME         NULL,
    [CreatedBy]                    UNIQUEIDENTIFIER NULL,
    [ModifiedOn]                   DATETIME         NULL,
    [ModifiedBy]                   UNIQUEIDENTIFIER NULL,
    [CreatedOnBehalfBy]            UNIQUEIDENTIFIER NULL,
    [ModifiedOnBehalfBy]           UNIQUEIDENTIFIER NULL,
    [OwnerId]                      UNIQUEIDENTIFIER NOT NULL,
    [OwnerIdType]                  INT              CONSTRAINT [DF_cgi_refundBase_OwnerIdType] DEFAULT ((8)) NOT NULL,
    [OwningBusinessUnit]           UNIQUEIDENTIFIER NULL,
    [statecode]                    INT              NOT NULL,
    [statuscode]                   INT              NULL,
    [VersionNumber]                ROWVERSION       NULL,
    [ImportSequenceNumber]         INT              NULL,
    [OverriddenCreatedOn]          DATETIME         NULL,
    [TimeZoneRuleVersionNumber]    INT              NULL,
    [UTCConversionTimeZoneCode]    INT              NULL,
    [cgi_refundnumber]             NVARCHAR (100)   NULL,
    [cgi_Amount]                   MONEY            NULL,
    [TransactionCurrencyId]        UNIQUEIDENTIFIER NULL,
    [ExchangeRate]                 DECIMAL (23, 10) NULL,
    [cgi_amount_Base]              MONEY            NULL,
    [cgi_AmountwithTAX]            MONEY            NULL,
    [cgi_amountwithtax_Base]       MONEY            NULL,
    [cgi_Attestation]              INT              NULL,
    [cgi_Quantity]                 INT              NULL,
    [cgi_Reference]                NVARCHAR (100)   NULL,
    [cgi_ReInvoicing]              BIT              NULL,
    [cgi_InvoiceRecipient]         UNIQUEIDENTIFIER NULL,
    [cgi_Accountid]                UNIQUEIDENTIFIER NULL,
    [cgi_Productid]                UNIQUEIDENTIFIER NULL,
    [cgi_RefundTypeid]             UNIQUEIDENTIFIER NULL,
    [cgi_ReimbursementFormid]      UNIQUEIDENTIFIER NULL,
    [cgi_Caseid]                   UNIQUEIDENTIFIER NULL,
    [cgi_car_reg]                  NVARCHAR (100)   NULL,
    [cgi_milage]                   DECIMAL (23, 10) NULL,
    [cgi_last_valid]               DATETIME         NULL,
    [cgi_milage_compensation]      DECIMAL (23, 10) NULL,
    [cgi_taxi_company]             NVARCHAR (100)   NULL,
    [cgi_transportcompanyid]       UNIQUEIDENTIFIER NULL,
    [cgi_auth_approved]            BIT              NULL,
    [cgi_amount_above_limit]       MONEY            NULL,
    [cgi_amount_above_limit_Base]  MONEY            NULL,
    [cgi_comments]                 NVARCHAR (MAX)   NULL,
    [cgi_value_code]               NVARCHAR (100)   NULL,
    [cgi_travelcard_number]        NVARCHAR (100)   NULL,
    [cgi_Contactid]                UNIQUEIDENTIFIER NULL,
    [cgi_responsibleId]            UNIQUEIDENTIFIER NULL,
    [cgi_soc_sec_number]           NVARCHAR (100)   NULL,
    [cgi_iban]                     NVARCHAR (100)   NULL,
    [cgi_swift]                    NVARCHAR (100)   NULL,
    [cgi_accountno]                NVARCHAR (100)   NULL,
    [cgi_foreign_payment]          NVARCHAR (100)   NULL,
    [cgi_vat_code]                 INT              NULL,
    [cgi_ExportedRaindance]        BIT              NULL,
    [cgi_ExportMessage]            NVARCHAR (MAX)   NULL,
    [cgi_ExportDate]               DATETIME         NULL,
    [cgi_checknumber]              NVARCHAR (100)   NULL,
    [cgi_attest_req]               NVARCHAR (100)   NULL,
    [cgi_IsAutoGenerated]          BIT              NULL,
    [cgi_EHOrderNumber]            NVARCHAR (50)    NULL,
    [cgi_CustomerMessage]          NVARCHAR (MAX)   NULL,
    [cgi_amount_limit_warn]        MONEY            NULL,
    [cgi_amount_limit_warn_Base]   MONEY            NULL,
    [cgi_MobileNumber]             NVARCHAR (100)   NULL,
    [cgi_email]                    NVARCHAR (100)   NULL,
    [cgi_errormessage]             NVARCHAR (200)   NULL,
    [cgi_mandcust]                 NVARCHAR (100)   NULL,
    [cgi_calculated_compensation]  DECIMAL (23, 10) NULL,
    [cgi_calculated_amount]        DECIMAL (23, 10) NULL,
    [cgi_value_code_used]          DATETIME         NULL,
    [cgi_invoiceexportdate]        DATETIME         NULL,
    [cgi_invoiceexportedraindance] BIT              NULL,
    [cgi_invoiceexportmessage]     NVARCHAR (MAX)   NULL,
    CONSTRAINT [PK_cgi_refundBase] PRIMARY KEY CLUSTERED ([cgi_refundId] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [business_unit_cgi_refund] FOREIGN KEY ([OwningBusinessUnit]) REFERENCES [dbo].[BusinessUnitBase] ([BusinessUnitId]) NOT FOR REPLICATION,
    CONSTRAINT [cgi_cgi_invoicerecipient_cgi_refund_InvoiceRecipient] FOREIGN KEY ([cgi_InvoiceRecipient]) REFERENCES [dbo].[cgi_invoicerecipientBase] ([cgi_invoicerecipientId]) NOT FOR REPLICATION,
    CONSTRAINT [cgi_cgi_refundaccount_cgi_refund_Accountid] FOREIGN KEY ([cgi_Accountid]) REFERENCES [dbo].[cgi_refundaccountBase] ([cgi_refundaccountId]) NOT FOR REPLICATION,
    CONSTRAINT [cgi_cgi_refundproduct_cgi_refund_Productid] FOREIGN KEY ([cgi_Productid]) REFERENCES [dbo].[cgi_refundproductBase] ([cgi_refundproductId]) NOT FOR REPLICATION,
    CONSTRAINT [cgi_cgi_refundtype_cgi_refund_RefundTypeid] FOREIGN KEY ([cgi_RefundTypeid]) REFERENCES [dbo].[cgi_refundtypeBase] ([cgi_refundtypeId]) NOT FOR REPLICATION,
    CONSTRAINT [cgi_cgi_reimbursementform_cgi_refund_ReimbursementFormid] FOREIGN KEY ([cgi_ReimbursementFormid]) REFERENCES [dbo].[cgi_reimbursementformBase] ([cgi_reimbursementformId]) NOT FOR REPLICATION,
    CONSTRAINT [cgi_contact_cgi_refund_Contactid] FOREIGN KEY ([cgi_Contactid]) REFERENCES [dbo].[ContactBase] ([ContactId]) NOT FOR REPLICATION,
    CONSTRAINT [cgi_incident_cgi_refund_Caseid] FOREIGN KEY ([cgi_Caseid]) REFERENCES [dbo].[IncidentBase] ([IncidentId]) NOT FOR REPLICATION,
    CONSTRAINT [cgi_refundresponsible_cgi_refund] FOREIGN KEY ([cgi_responsibleId]) REFERENCES [dbo].[cgi_refundresponsibleBase] ([cgi_refundresponsibleId]) NOT FOR REPLICATION,
    CONSTRAINT [cgi_transportcompany_refund] FOREIGN KEY ([cgi_transportcompanyid]) REFERENCES [dbo].[cgi_transportcompanyBase] ([cgi_transportcompanyId]) NOT FOR REPLICATION,
    CONSTRAINT [owner_cgi_refund] FOREIGN KEY ([OwnerId]) REFERENCES [dbo].[OwnerBase] ([OwnerId]) NOT FOR REPLICATION
);


GO
CREATE NONCLUSTERED INDEX [ndx_Security]
    ON [dbo].[cgi_refundBase]([OwnerId] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [ndx_Core]
    ON [dbo].[cgi_refundBase]([statecode] ASC, [statuscode] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [ndx_Sync]
    ON [dbo].[cgi_refundBase]([VersionNumber] ASC) WHERE ([VersionNumber] IS NOT NULL) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [ndx_cgi_refundnumber]
    ON [dbo].[cgi_refundBase]([cgi_refundnumber] ASC) WITH (FILLFACTOR = 80);

