//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SR.Generated
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/abssr/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("abssr_AddressLookup")]
	public partial class abssr_AddressLookupResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public abssr_AddressLookupResponse()
		{
		}
		
		public string ApiResponseMessage
		{
			get
			{
				if (this.Results.Contains("ApiResponseMessage"))
				{
					return ((string)(this.Results["ApiResponseMessage"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public bool Success
		{
			get
			{
				if (this.Results.Contains("Success"))
				{
					return ((bool)(this.Results["Success"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
	}
}