//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SR.Generated
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/abssr/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("abssr_CreatePermit")]
	public partial class abssr_CreatePermitResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public abssr_CreatePermitResponse()
		{
		}
	}
}