"C:\Program Files\QlikView\qv.exe" /r "C:\QlikView\Applikationer\Update_QVD.qvw"
"C:\Program Files\QlikView\qv.exe" /r "C:\QlikView\Applikationer\UpdateTravelCardTot.qvw"
"C:\Program Files\QlikView\qv.exe" /r "C:\QlikView\Applikationer\Import_Singapore_Tickets.qvw"
"C:\Program Files\QlikView\qv.exe" /r "C:\QlikView\Applikationer\Update_LatestTravelDate.qvw"
"C:\Program Files\QlikView\qv.exe" /r "C:\QlikView\Applikationer\ImportTravelDays.qvw" 
"C:\Program Files\QlikView\qv.exe" /r "C:\QlikView\Applikationer\Import_SalesOrder.qvw"
"C:\Program Files\QlikView\qv.exe" /r "C:\QlikView\Applikationer\Dubbletter SSN1 och SSN2.qvw" 
"C:\Program Files\QlikView\qv.exe" /r "C:\QlikView\Applikationer\Dubbletter namn och e-post.qvw"
"C:\Program Files\QlikView\qv.exe" /r "C:\QlikView\Applikationer\MittKonto_Analys.qvw"